// 한국관광공사 TourAPI 공식 검증 전국 주요 관광명소 데이터베이스
// AI의 임의 지명 생성을 원천 차단하고, 100% 실존하는 공공데이터 관광명소 정보 제공

export interface VerifiedLandmark {
  name: string;
  region: string;
  address: string;
  latitude: number;
  longitude: number;
  category: string;
  targetDurationMinutes: number;
  titleReward: string;
  badgeIcon: string;
  description: string;
  imageUrl?: string;
  naverPlaceName: string;
}

export const VERIFIED_REGIONAL_LANDMARKS: VerifiedLandmark[] = [
  // 1. 서울
  {
    name: "남산 N서울타워 & 둘레길",
    region: "서울",
    address: "서울특별시 중구 남산공원길 105",
    latitude: 37.5512,
    longitude: 126.9882,
    category: "산책로/자연",
    targetDurationMinutes: 30,
    titleReward: "남산 솔향 웰니스 마스터 🏅",
    badgeIcon: "🌲",
    description: "피톤치드 가득한 남산 소나무 자락길을 완보하여 식후 혈당과 혈압을 안정화하세요.",
    naverPlaceName: "N서울타워",
  },
  {
    name: "덕수궁 돌담길 & 정동길",
    region: "서울",
    address: "서울특별시 중구 정동 덕수궁길 24",
    latitude: 37.5662,
    longitude: 126.9765,
    category: "역사문화/도심",
    targetDurationMinutes: 20,
    titleReward: "정동 역사문화 탐험가 🌿",
    badgeIcon: "🏛️",
    description: "계단 없는 완벽한 평지 돌담길을 산책하며 활력을 충전하고 자율신경계를 이완합니다.",
    naverPlaceName: "덕수궁 돌담길",
  },
  {
    name: "청계천 무장애 수변길",
    region: "서울",
    address: "서울특별시 중구 태평로1가 청계광장",
    latitude: 37.5691,
    longitude: 126.9786,
    category: "수변/도심",
    targetDurationMinutes: 25,
    titleReward: "청계천 물빛 활력왕 💧",
    badgeIcon: "🌊",
    description: "물소리를 들으며 도심 속 힐링을 누리는 보행 전용 데크길입니다.",
    naverPlaceName: "청계광장",
  },
  {
    name: "용산가족공원 호수 둘레길",
    region: "서울",
    address: "서울특별시 용산구 서빙고로 185",
    latitude: 37.5228,
    longitude: 126.9814,
    category: "호수/공원",
    targetDurationMinutes: 25,
    titleReward: "용산 수변 힐링 수호자 🌿",
    badgeIcon: "🦆",
    description: "넓은 잔디밭과 잔잔한 호수를 끼고 걷는 완만한 평지 웰니스 코스입니다.",
    naverPlaceName: "용산가족공원",
  },
  {
    name: "삼청공원 숲속 무장애 데크길",
    region: "서울",
    address: "서울특별시 종로구 삼청로 139",
    latitude: 37.5875,
    longitude: 126.9845,
    category: "숲길/산책로",
    targetDurationMinutes: 30,
    titleReward: "북악 솔숲 보행 마스터 🌲",
    badgeIcon: "🌲",
    description: "피톤치드 숲속 쉼터와 무장애 목재 데크로 조성된 고요한 치유 공간입니다.",
    naverPlaceName: "삼청공원",
  },
  {
    name: "서울숲 은행나무길 & 수변 쉼터",
    region: "서울",
    address: "서울특별시 성동구 뚝섬로 273",
    latitude: 37.5444,
    longitude: 127.0374,
    category: "자연공원",
    targetDurationMinutes: 30,
    titleReward: "서울숲 푸른숨 웰니스 챔피언 🌿",
    badgeIcon: "🌳",
    description: "생태숲과 호수가 조화를 이루는 서울 동부 대표 무장애 평지 힐링 명소입니다.",
    naverPlaceName: "서울숲",
  },

  // 2. 안산
  {
    name: "안산 호수공원 수변 힐링로",
    region: "안산",
    address: "경기도 안산시 상록구 해봉로 32",
    latitude: 37.3015,
    longitude: 126.8310,
    category: "수변공원",
    targetDurationMinutes: 25,
    titleReward: "안산호수 은빛 갈대 마스터 🌾",
    badgeIcon: "🌊",
    description: "갈대와 호수가 어우러진 넓고 평탄한 보행 전용로로 심박수 안정과 혈압 관리에 탁월합니다.",
    naverPlaceName: "안산호수공원",
  },
  {
    name: "안산 화랑유원지 수변 둘레길",
    region: "안산",
    address: "경기도 안산시 단원구 동산로 268",
    latitude: 37.3235,
    longitude: 126.8124,
    category: "유원지/호수",
    targetDurationMinutes: 25,
    titleReward: "화랑유원지 힐링 보행왕 🌿",
    badgeIcon: "🦆",
    description: "사계절 수변 풍경을 감상하며 걷는 단원구 대표 평지 산책 코스입니다.",
    naverPlaceName: "화랑유원지",
  },
  {
    name: "노적봉공원 장미원 & 인공폭포 평지길",
    region: "안산",
    address: "경기도 안산시 상록구 성포동 산39-1",
    latitude: 37.3308,
    longitude: 126.8482,
    category: "공원/폭포",
    targetDurationMinutes: 20,
    titleReward: "노적봉 청량 폭포 힐러 💧",
    badgeIcon: "🌹",
    description: "시원한 인공폭포 물소리와 계단 없는 순환로를 즐기며 보행 활력을 회복하세요.",
    naverPlaceName: "노적봉공원",
  },
  {
    name: "선부 샛터공원 & 선부광장 둘레길",
    region: "안산",
    address: "경기도 안산시 단원구 선부동 1081",
    latitude: 37.3392,
    longitude: 126.8065,
    category: "도심공원",
    targetDurationMinutes: 20,
    titleReward: "선부 달미 숲길 탐험가 🌲",
    badgeIcon: "🌿",
    description: "선부역 인근 도심 생활권 숲길로 노약자도 부담 없이 걷는 평탄 보행로입니다.",
    naverPlaceName: "샛터공원",
  },
  {
    name: "안산 갈대습지공원 생태 둘레길",
    region: "안산",
    address: "경기도 안산시 상록구 갈대습지로 76",
    latitude: 37.2798,
    longitude: 126.8405,
    category: "생태습지/자연",
    targetDurationMinutes: 30,
    titleReward: "안산습지 자연치유 수호자 🌾",
    badgeIcon: "🪶",
    description: "시화호 상류 국내 최초 인공습지에서 철새와 갈대숲을 벗 삼는 생태 완보길입니다.",
    naverPlaceName: "안산갈대습지공원",
  },
  {
    name: "대부도 해솔길 1코스 낙조길",
    region: "안산",
    address: "경기도 안산시 단원구 대부북동 산23",
    latitude: 37.2882,
    longitude: 126.5824,
    category: "해안트레킹",
    targetDurationMinutes: 30,
    titleReward: "대부도 서해낙조 걷기왕 🌅",
    badgeIcon: "🌅",
    description: "서해 바다와 솔숲이 맞닿은 시원한 해풍 트레킹으로 심폐 활력을 북돋웁니다.",
    naverPlaceName: "대부해솔길",
  },

  // 3. 수원
  {
    name: "광교호수공원 어반레비 수변 둘레길",
    region: "수원",
    address: "경기도 수원시 영통구 광교호수로 102",
    latitude: 37.2845,
    longitude: 127.0655,
    category: "호수공원",
    targetDurationMinutes: 30,
    titleReward: "광교 호수빛 웰니스 마스터 🏅",
    badgeIcon: "🌊",
    description: "국내 최대 규모 도심 호수공원으로 완만한 목재 데크와 조명이 아름다운 치유로입니다.",
    naverPlaceName: "광교호수공원",
  },
  {
    name: "수원화성 성곽길 & 방화수류정 평지 산책",
    region: "수원",
    address: "경기도 수원시 팔달구 수원천로392번길 44-6",
    latitude: 37.2884,
    longitude: 127.0189,
    category: "세계문화유산",
    targetDurationMinutes: 25,
    titleReward: "수원화성 역사누리 완보왕 🏛️",
    badgeIcon: "🏯",
    description: "유네스코 세계문화유산 수원화성의 수려한 연못과 성곽길을 따라 걷는 명소입니다.",
    naverPlaceName: "방화수류정",
  },
  {
    name: "서호공원 철새도래지 둘레길",
    region: "수원",
    address: "경기도 수원시 팔달구 덕영대로 924",
    latitude: 37.2755,
    longitude: 126.9892,
    category: "호수/자연",
    targetDurationMinutes: 25,
    titleReward: "서호 낙조 힐링 탐험가 🦆",
    badgeIcon: "🌾",
    description: "축만제를 끼고 소나무 숲길과 수변 평지 산책로가 조성된 도심 휴식처입니다.",
    naverPlaceName: "서호공원",
  },

  // 4. 고양
  {
    name: "일산호수공원 무장애 수변 둘레길",
    region: "고양",
    address: "경기도 고양시 일산동구 호수로 595",
    latitude: 37.6542,
    longitude: 126.7702,
    category: "호수공원",
    targetDurationMinutes: 30,
    titleReward: "일산호수 초록숨 완보왕 🌿",
    badgeIcon: "🌸",
    description: "동양 최대 인공호수를 따라 메타세쿼이아길과 꽃길이 펼쳐지는 국민 힐링 명소입니다.",
    naverPlaceName: "일산호수공원",
  },
  {
    name: "행주산성 역사누리 평지 둘레길",
    region: "고양",
    address: "경기도 고양시 덕양구 행주로15번길 89",
    latitude: 37.5954,
    longitude: 126.8182,
    category: "역사문화",
    targetDurationMinutes: 25,
    titleReward: "행주나루 한강바람 수호자 🌊",
    badgeIcon: "🏛️",
    description: "한강 하류를 조망하며 역사적인 충의정을 잇는 숲길 코스입니다.",
    naverPlaceName: "행주산성역사공원",
  },

  // 5. 성남
  {
    name: "성남 율동공원 호수 완만 둘레길",
    region: "성남",
    address: "경기도 성남시 분당구 문정로 145",
    latitude: 37.3775,
    longitude: 127.1485,
    category: "호수공원",
    targetDurationMinutes: 25,
    titleReward: "분당 율동호수 힐링 마스터 🌿",
    badgeIcon: "🦢",
    description: "대형 분수와 갈대숲, 조각공원이 어우러진 분당 대표 웰니스 명소입니다.",
    naverPlaceName: "율동공원",
  },
  {
    name: "탄천 수변 무장애 자전거·보행로",
    region: "성남",
    address: "경기도 성남시 분당구 정자동 1",
    latitude: 37.3654,
    longitude: 127.1082,
    category: "하천/수변",
    targetDurationMinutes: 25,
    titleReward: "탄천 푸른물길 활력 걷기왕 💧",
    badgeIcon: "🏃",
    description: "경사도가 전혀 없는 완전 평지로 어르신과 재활 보행자에게 최적화된 수변길입니다.",
    naverPlaceName: "탄천",
  },

  // 6. 인천
  {
    name: "송도 센트럴파크 해수공원 수변 산책로",
    region: "인천",
    address: "인천광역시 연수구 컨벤시아대로 160",
    latitude: 37.3925,
    longitude: 126.6335,
    category: "도심/해수공원",
    targetDurationMinutes: 30,
    titleReward: "송도 미래도시 웰니스 탐험가 🏙️",
    badgeIcon: "🌊",
    description: "국내 최초 바닷물을 끌어들인 해수공원에서 이색적인 빌딩 숲과 자연을 만끽하세요.",
    naverPlaceName: "송도센트럴파크",
  },
  {
    name: "인천 자유공원 & 차이나타운 역사언덕길",
    region: "인천",
    address: "인천광역시 중구 자유공원남로 25",
    latitude: 37.4745,
    longitude: 126.6215,
    category: "역사문화",
    targetDurationMinutes: 25,
    titleReward: "개항장 문화거리 완보왕 🏛️",
    badgeIcon: "🚢",
    description: "한국 최초의 서양식 공원으로 인천항과 서해 낙조를 한눈에 굽어봅니다.",
    naverPlaceName: "자유공원",
  },

  // 7. 대전
  {
    name: "대전 한밭수목원 서원 힐링 둘레길",
    region: "대전",
    address: "대전광역시 서구 둔산대로 169",
    latitude: 36.3685,
    longitude: 127.3882,
    category: "도심수목원",
    targetDurationMinutes: 30,
    titleReward: "한밭 푸른솔 웰니스 수호자 🌲",
    badgeIcon: "🌿",
    description: "중부권 최대 규모 도심 인공수목원으로 솔바람길과 침엽수림이 장관을 이룹니다.",
    naverPlaceName: "한밭수목원",
  },
  {
    name: "엑스포다리 & 갑천 수변 데크로드",
    region: "대전",
    address: "대전광역시 유성구 도룡동 3-1",
    latitude: 36.3752,
    longitude: 127.3835,
    category: "수변/도심",
    targetDurationMinutes: 20,
    titleReward: "갑천 물결 활력 워커 💧",
    badgeIcon: "🌉",
    description: "갑천의 시원한 강바람을 맞으며 엑스포 과학공원을 조망하는 평지 산책로입니다.",
    naverPlaceName: "엑스포다리",
  },

  // 8. 세종
  {
    name: "세종호수공원 물빛섬 수상데크길",
    region: "세종",
    address: "세종특별자치시 연기면 다솜로 216",
    latitude: 36.5005,
    longitude: 127.2695,
    category: "호수공원",
    targetDurationMinutes: 30,
    titleReward: "세종 푸른물빛 힐링 챔피언 🌊",
    badgeIcon: "🏝️",
    description: "축구장 62개 크기의 국내 최대 인공호수에서 수상무대섬과 백사장을 걷는 웰니스 명소입니다.",
    naverPlaceName: "세종호수공원",
  },

  // 9. 대구
  {
    name: "대구 수성못 수변 데크 완만 둘레길",
    region: "대구",
    address: "대구광역시 수성구 두산동 512",
    latitude: 35.8275,
    longitude: 128.6185,
    category: "수변호수",
    targetDurationMinutes: 25,
    titleReward: "수성못 은빛물결 걷기왕 🦢",
    badgeIcon: "🌊",
    description: "탁 트인 호수 전경과 버드나무 그늘이 드리워진 대구 최고의 산책 코스입니다.",
    naverPlaceName: "수성못",
  },

  // 10. 부산
  {
    name: "해운대 동백섬 무장애 해안산책로",
    region: "부산",
    address: "부산광역시 해운대구 우동 710-1",
    latitude: 35.1535,
    longitude: 129.1525,
    category: "해안둘레길",
    targetDurationMinutes: 30,
    titleReward: "해운대 파도소리 웰니스 마스터 🌊",
    badgeIcon: "🌺",
    description: "동백꽃과 울창한 해송, 누리마루 APEC하우스가 어우러진 환상적인 해안 완보길입니다.",
    naverPlaceName: "동백섬",
  },
  {
    name: "광안리 해변 테라스 데크로드",
    region: "부산",
    address: "부산광역시 수영구 광안해변로 219",
    latitude: 35.1532,
    longitude: 129.1185,
    category: "해변산책로",
    targetDurationMinutes: 25,
    titleReward: "광안대교 바다바람 활력왕 🌉",
    badgeIcon: "🏖️",
    description: "광안대교의 웅장한 오션뷰와 모래사장 테두리 평지 데크를 따라 걷는 코스입니다.",
    naverPlaceName: "광안리해수욕장",
  },

  // 11. 광주
  {
    name: "광주 5·18기념공원 단풍나무 무장애 둘레길",
    region: "광주",
    address: "광주광역시 서구 내방로 152",
    latitude: 35.1555,
    longitude: 126.8575,
    category: "도심추모공원",
    targetDurationMinutes: 25,
    titleReward: "빛고을 평화숲 힐링 마스터 🕊️",
    badgeIcon: "🍁",
    description: "울창한 수목과 전통 누각 대동정이 자리한 상무지구 중심의 안심 평지 산책로입니다.",
    naverPlaceName: "5·18기념공원",
  },

  // 12. 강릉
  {
    name: "강릉 경포호수 수변 무장애 둘레길",
    region: "강릉",
    address: "강원특별자치도 강릉시 저동 94",
    latitude: 37.7995,
    longitude: 128.9055,
    category: "석호/생태",
    targetDurationMinutes: 30,
    titleReward: "경포 솔향호수 웰니스 완보왕 🌲",
    badgeIcon: "🦢",
    description: "거울처럼 맑은 경포호와 울창한 해송림을 벗 삼아 완보하는 강릉 대표 힐링 코스입니다.",
    naverPlaceName: "경포호",
  },
  {
    name: "강릉 오죽헌 대나무숲 힐링길",
    region: "강릉",
    address: "강원특별자치도 강릉시 율곡로3139번길 24",
    latitude: 37.7792,
    longitude: 128.8785,
    category: "역사문화",
    targetDurationMinutes: 20,
    titleReward: "율곡 사임당 선비길 탐험가 🎋",
    badgeIcon: "🎋",
    description: "검은 대나무 오죽이 바람에 흔들리는 청량한 소리를 들으며 심신을 정화합니다.",
    naverPlaceName: "오죽헌",
  },

  // 13. 전주
  {
    name: "전주 덕진공원 연화교 수변 평지길",
    region: "전주",
    address: "전북특별자치도 전주시 덕진구 권삼득로 390",
    latitude: 35.8495,
    longitude: 127.1215,
    category: "전통호수",
    targetDurationMinutes: 25,
    titleReward: "전주 연꽃향기 웰니스 힐러 🪷",
    badgeIcon: "🪷",
    description: "연꽃이 장관을 이루는 전통 연화정과 목재 수변 데크를 천천히 음미하며 걷습니다.",
    naverPlaceName: "덕진공원",
  },

  // 14. 순천
  {
    name: "순천만습지 무장애 갈대숲 데크로드",
    region: "순천",
    address: "전라남도 순천시 순천만길 513-25",
    latitude: 34.8875,
    longitude: 127.5095,
    category: "연안습지",
    targetDurationMinutes: 30,
    titleReward: "순천만 생태 갈대숲 수호자 🌾",
    badgeIcon: "🦀",
    description: "세계 5대 연안습지인 순천만의 은빛 갈대밭 사이를 휠체어로도 편안하게 산책합니다.",
    naverPlaceName: "순천만습지",
  },

  // 15. 제주
  {
    name: "절물자연휴양림 무장애 삼나무 데크길",
    region: "제주",
    address: "제주특별자치도 제주시 명림로 584",
    latitude: 33.4385,
    longitude: 126.6295,
    category: "자연휴양림",
    targetDurationMinutes: 30,
    titleReward: "제주 삼나무숲 피톤치드 힐러 🌲",
    badgeIcon: "🦌",
    description: "빽빽한 삼나무 숲길에 턱 없는 목재 데크가 설치되어 누구나 호흡하기 좋은 치유의 숲입니다.",
    naverPlaceName: "절물자연휴양림",
  },
  {
    name: "제주 사려니숲길 붉은오름 무장애 나눔길",
    region: "제주",
    address: "제주특별자치도 서귀포시 표선면 가시리 산158-4",
    latitude: 33.4025,
    longitude: 126.6855,
    category: "원시림숲길",
    targetDurationMinutes: 30,
    titleReward: "사려니 원시림 웰니스 마스터 🌿",
    badgeIcon: "🌲",
    description: "신성한 숲이라는 뜻의 사려니숲에서 화산송이 흙길과 데크를 밟으며 활력을 되찾습니다.",
    naverPlaceName: "사려니숲길",
  },

  // 16. 영양
  {
    name: "영양 삼지연꽃테마파크 수변 데크 평지길",
    region: "영양",
    address: "경상북도 영양군 영양읍 삼지리 172",
    latitude: 36.6525,
    longitude: 129.1215,
    category: "수변생태",
    targetDurationMinutes: 25,
    titleReward: "영양 밤하늘 별빛 완보왕 🌟",
    badgeIcon: "🪷",
    description: "아시아 최초 국제밤하늘보호공원 영양의 청정 호수변 연꽃 테마길입니다.",
    naverPlaceName: "삼지연꽃테마파크",
  },

  // 17. 안동
  {
    name: "월영교 수변 무장애 데크로드",
    region: "안동",
    address: "경상북도 안동시 상아동 569",
    latitude: 36.5765,
    longitude: 128.7585,
    category: "수변목교",
    targetDurationMinutes: 25,
    titleReward: "안동 월영 달빛 웰니스 챔피언 🌙",
    badgeIcon: "🌉",
    description: "국내 최장의 목책 인도교로 낙동강 물길 위를 부드럽게 가로지르는 낭만 완보길입니다.",
    naverPlaceName: "월영교",
  },
];
