import {
  WellnessCourseSet,
  UserProfile,
  MultiDayCourseSet,
  WellnessStay,
  WellnessQuest,
} from "../types/wellness.types";

export const INITIAL_USER_PROFILE: UserProfile = {
  userName: "관광 여행자",
  chronicConditions: ["당뇨", "고혈압"],
  allergies: ["갑각류", "땅콩"],
  dietaryPreference: "저염/저탄수화물",
  conditionToday: "식후 30분 가벼운 평지 산책 희망",
};

export const INITIAL_WELLNESS_COURSES: WellnessCourseSet[] = [
  {
    id: "course-1",
    title: "1코스: [당뇨케어] 자연 쌈채 밥상 ➔ 남산 소나무 자락길",
    targetCondition: "당뇨 (급격한 혈당 스파이크 방지)",
    restaurant: {
      id: "rest-1",
      name: "소담한 자연밥상",
      category: "안심식당",
      description: "당 지수(GI) 50 이하 유기농 현미와 제철 저염 나물 요리 전문점",
      address: "서울특별시 중구 소파로 83",
      latitude: 37.5583,
      longitude: 126.9825,
      safeTags: ["GI지수 낮음", "저염식", "친환경채소"],
      healthBenefit: "복합 탄수화물 식단으로 완만한 인슐린 분비 유도",
      nutrition: {
        menuName: "유기농 제철 쌈채 밥상",
        calories: 420,
        carbohydrate: 58,
        sugars: 4,
        sodium: 380,
        protein: 16,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 4g(안심), 나트륨 380mg(안심)의 완벽한 당뇨 케어 식단",
      },
      tourApiContentId: "FD010100_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-1",
      name: "남산 힐링 소나무 자락길",
      category: "산책로",
      description: "경사도 4.5% 미만의 휠체어/시니어 완만 무장애 목재 데크길",
      address: "서울특별시 중구 회현동 남산공원 자락길",
      latitude: 37.5545,
      longitude: 126.9850,
      safeTags: ["완경사 5%미만", "무장애 데크", "쉼터 완비"],
      healthBenefit: "식후 30분 완보로 근육의 포도당 흡수율 40% 증가",
      tourApiContentId: "C010100_01",
      isMajorRoute: true,
    },
    walkMinutes: 41,
    distanceMeters: 1000,
    walkingRoute: [
      [126.9825, 37.5583],   // 소담한 자연밥상 (출발지 마커 완벽 일치)
      [126.9827, 37.55775],  // 소파로 하행
      [126.98305, 37.5571],  // 소파로 삼거리
      [126.98335, 37.55645], // 남산케이블카 매점, 촛불1978 앞
      [126.98315, 37.5558],  // 소파로 커브 진입로
      [126.9827, 37.5554],   // 굽이치는 도로 구간
      [126.9821, 37.55505],  // 서측 굽이길
      [126.9818, 37.5548],   // 첫 번째 헤어핀 U턴 지점 (체육센터 북측)
      [126.98215, 37.5546],  // U턴 회전 구간
      [126.98275, 37.55435], // 소파로 하단 도로
      [126.9831, 37.5541],   // 두 번째 헤어핀 반전 지점
      [126.98345, 37.55435], // 북동향 소월로 연결 보행로 진입
      [126.98365, 37.5547],  // 보행 데크길 입구
      [126.9839, 37.55495],  // 조지훈 시비 남측 연결로
      [126.98425, 37.5548],  // 목멱산방 방향 숲길 보행로
      [126.9845, 37.55455],  // 목멱산방 앞
      [126.98475, 37.5544],  // 소나무 자락길 데크길 초입
      [126.9850, 37.5545],   // 남산 힐링 소나무 자락길 종점 (도착지 마커 완벽 일치)
    ],
    // 이동 동선 중간 도보 3~5분 공공 편의시설 (Tour API detailInfo2 연계)
    waypoints: [
      {
        id: "wp-1-1",
        name: "남산공원 안심 공중화장실",
        category: "화장실",
        description: "고혈압·시니어 보행 약자를 위한 상시 개방형 청결 안심화장실",
        address: "서울특별시 중구 소파로 95",
        latitude: 37.5566,
        longitude: 126.9841,
        walkingMinutesFromRoute: 3,
        distanceMetersFromRoute: 150,
        features: ["장애인 화장실", "비데 완비", "안심 비상벨", "온수 공급"],
      },
      {
        id: "wp-1-2",
        name: "소나무숲 그늘 팔각정 쉼터",
        category: "쉼터",
        description: "피로 누적 시 즉시 휴식할 수 있는 솔숲 그늘 벤치와 정자",
        address: "서울특별시 중구 남산공원 소나무숲길 중턱",
        latitude: 37.5558,
        longitude: 126.9834,
        walkingMinutesFromRoute: 4,
        distanceMetersFromRoute: 190,
        features: ["목재 평상", "그늘 벤치", "음수대", "피톤치드 풍부"],
      },
      {
        id: "wp-1-3",
        name: "남산 무장애 경사로 & 쉼터",
        category: "배리어프리",
        description: "휠체어 및 보행 보조기 이용자를 위한 단차 없는 완경사 데크",
        address: "서울특별시 중구 회현동1가 산1-16",
        latitude: 37.5572,
        longitude: 126.9832,
        walkingMinutesFromRoute: 5,
        distanceMetersFromRoute: 240,
        features: ["경사도 3.8% 완경사", "점자 유도블록", "휠체어 쉼터"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 최고 혈당 25mg/dL 억제 및 피로 회복",
  },
  {
    id: "course-2",
    title: "2코스: [고혈압케어] 저염 메밀 정식 ➔ 용산가족공원 호수길",
    targetCondition: "고혈압 (나트륨 배출 및 혈관 이완)",
    restaurant: {
      id: "rest-2",
      name: "도심속 풀향기 건강식당",
      category: "안심식당",
      description: "염도 0.5% 이하 안심 인증 식당, 루틴 성분 풍부한 순메밀 요리",
      address: "서울특별시 용산구 이태원로 29",
      latitude: 37.5348,
      longitude: 126.9942,
      safeTags: ["염도 0.5%이하", "칼륨 풍부", "루틴 함유"],
      healthBenefit: "나트륨 배출 및 모세혈관 탄력성 강화",
      nutrition: {
        menuName: "메밀 순면 맑은 정식",
        calories: 460,
        carbohydrate: 64,
        sugars: 3,
        sodium: 310,
        protein: 14,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 나트륨 310mg(안심)으로 일반 외식(1,200mg) 대비 74% 나트륨 저감",
      },
      tourApiContentId: "FD010200_02",
      isMajorRoute: false,
    },
    trail: {
      id: "trail-2",
      name: "용산가족공원 호수 둘레길",
      category: "산책로",
      description: "호수를 감싸는 평탄한 흙길과 그늘 벤치가 잘 조성된 회복로",
      address: "서울특별시 용산구 서빙고로 185",
      latitude: 37.5242,
      longitude: 126.9805,
      safeTags: ["완벽 평지", "호수 뷰", "넓은 보행로"],
      healthBenefit: "안정된 심박수와 자율신경계 긴장 완화로 혈압 강하",
      tourApiContentId: "C010200_02",
      isMajorRoute: false,
    },
    walkMinutes: 25,
    distanceMeters: 1850,
    walkingRoute: [
      [126.9942, 37.5348],
      [126.9915, 37.5345],
      [126.9875, 37.5340],
      [126.9868, 37.5312],
      [126.9855, 37.5275],
      [126.9830, 37.5255],
      [126.9805, 37.5242],
    ],
    waypoints: [
      {
        id: "wp-2-1",
        name: "용산가족공원 입구 청결화장실",
        category: "화장실",
        description: "이뇨제 복용 환자가 급히 찾을 수 있는 넓은 다목적 공중화장실",
        address: "서울특별시 용산구 서빙고로 185 잔디광장 앞",
        latitude: 37.5256,
        longitude: 126.9822,
        walkingMinutesFromRoute: 3,
        distanceMetersFromRoute: 140,
        features: ["장애인 화장실", "냉난방 완비", "기저귀 교환대", "자동 손세정"],
      },
      {
        id: "wp-2-2",
        name: "호수변 버드나무 그늘 벤치 쉼터",
        category: "쉼터",
        description: "물소리를 들으며 혈압과 심박수를 안정시킬 수 있는 평탄 쉼터",
        address: "서울특별시 용산구 서빙고동 호수둘레길 2지점",
        latitude: 37.5249,
        longitude: 126.9814,
        walkingMinutesFromRoute: 3,
        distanceMetersFromRoute: 170,
        features: ["호수 전망 벤치", "그늘막", "자동 혈압계 비치"],
      },
      {
        id: "wp-2-3",
        name: "국립중앙박물관 무장애 평지 통로",
        category: "배리어프리",
        description: "계단 없이 평지만으로 공원과 박물관을 잇는 안전 보행로",
        address: "서울특별시 용산구 서빙고로 137 연결통로",
        latitude: 37.5262,
        longitude: 126.9835,
        walkingMinutesFromRoute: 5,
        distanceMetersFromRoute: 260,
        features: ["전동휠체어 급속충전기", "단차 제로 평지", "야간 안심조명"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "수축기 혈압 8~10mmHg 일시적 하강 효과",
  },
  {
    id: "course-3",
    title: "3코스: [복합대사케어] 한옥 버섯전골 ➔ 삼청공원 피톤치드 숲길",
    targetCondition: "복합 대사증후군 (체지방 연소 & 면역)",
    restaurant: {
      id: "rest-3",
      name: "한옥 채움 약선당",
      category: "안심식당",
      description: "베타글루칸 풍부한 자연산 버섯 전골과 찰보리 솥밥",
      address: "서울특별시 종로구 북촌로 42",
      latitude: 37.5815,
      longitude: 126.9855,
      safeTags: ["베타글루칸", "무가당", "면역 증진"],
      healthBenefit: "콜레스테롤 개선 및 장내 미생물 균형",
      nutrition: {
        menuName: "자연산 모둠 버섯전골",
        calories: 440,
        carbohydrate: 52,
        sugars: 5,
        sodium: 420,
        protein: 20,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 식이섬유 12g, 당류 5g(안심)으로 인슐린 저항성 완화",
      },
      tourApiContentId: "FD010100_03",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-3",
      name: "삼청공원 숲속 무장애 데크길",
      category: "산책로",
      description: "소나무와 단풍나무 사이로 피톤치드가 뿜어져 나오는 숲길",
      address: "서울특별시 종로구 삼청로 156",
      latitude: 37.5890,
      longitude: 126.9840,
      safeTags: ["숲속 산소", "완만 데크", "피톤치드"],
      healthBenefit: "산소 섭취량 증가 및 림프 순환 활성화",
      tourApiContentId: "C010300_03",
      isMajorRoute: true,
    },
    walkMinutes: 35,
    distanceMeters: 920,
    walkingRoute: [
      [126.9855, 37.5815],
      [126.9852, 37.5830],
      [126.9848, 37.5850],
      [126.9845, 37.5870],
      [126.9840, 37.5890],
    ],
    waypoints: [
      {
        id: "wp-3-1",
        name: "삼청공원 숲속 안심화장실",
        category: "화장실",
        description: "공원 입구에 위치한 장애물 없는 청결 안심화장실",
        address: "서울특별시 종로구 북촌로 137 삼청공원 입구",
        latitude: 37.5872,
        longitude: 126.9842,
        walkingMinutesFromRoute: 3,
        distanceMetersFromRoute: 160,
        features: ["장애인 화장실", "안심 비상벨", "온수 공급", "24시간 개방"],
      },
      {
        id: "wp-3-2",
        name: "피톤치드 소나무 정자 쉼터",
        category: "쉼터",
        description: "삼청동 전경을 조망하며 쉴 수 있는 힐링 마루 쉼터",
        address: "서울특별시 종로구 삼청동 삼청공원 둘레길",
        latitude: 37.5855,
        longitude: 126.9850,
        walkingMinutesFromRoute: 4,
        distanceMetersFromRoute: 200,
        features: ["목재 정자", "그늘막 벤치", "숲속 산소 쉼터"],
      },
      {
        id: "wp-3-3",
        name: "북촌 전통문화 무장애 쉼터",
        category: "배리어프리",
        description: "전통 한옥 양식으로 지어진 보행 약자 휴게 쉼터",
        address: "서울특별시 종로구 계동길 37",
        latitude: 37.5832,
        longitude: 126.9858,
        walkingMinutesFromRoute: 4,
        distanceMetersFromRoute: 180,
        features: ["단차 없는 출입구", "안내 점자", "휴식 다도 쉼터"],
      },
    ],
    slopeGrade: "보통",
    expectedEffect: "기초대사량 증진 및 코르티솔(스트레스 호르몬) 30% 감소",
  },
  {
    id: "course-4",
    title: "4코스: [저혈압케어] 고단백 영양 솥밥 ➔ 덕수궁 돌담길 평지 산책",
    targetCondition: "저혈압 (식후 저혈압·어지럼증 방지 식후 필수 산책)",
    restaurant: {
      id: "rest-4",
      name: "정동 온반 건강 솥밥",
      category: "안심식당",
      description: "양질의 단백질과 미네랄이 풍부한 영양 전복 솥밥과 따뜻한 건강 온반",
      address: "서울특별시 중구 정동길 12",
      latitude: 37.5658,
      longitude: 126.9742,
      safeTags: ["고단백", "적정 미네랄", "온기 보양"],
      healthBenefit: "식후 소화 흡수 촉진 및 혈액 순환 개선",
      nutrition: {
        menuName: "영양 전복 버섯 솥밥 정식",
        calories: 480,
        carbohydrate: 62,
        sugars: 3,
        sodium: 490,
        protein: 24,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 단백질 24g, 적정 나트륨 490mg(안심)으로 식후 혈압 급강하 방지",
      },
      tourApiContentId: "FD010100_04",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-4",
      name: "덕수궁 돌담길 평지 산책로",
      category: "산책로",
      description: "식당 바로 앞 계단 없는 100% 완전 평지 보행로 (식후 20분 완보로 하지 혈액 순환 촉진)",
      address: "서울특별시 중구 정동 덕수궁길 24",
      latitude: 37.5662,
      longitude: 126.9765,
      safeTags: ["완전 평지 0%", "보행 전용길", "가로수 그늘"],
      healthBenefit: "종아리 근육 펌핑을 통해 심장으로의 정맥혈 회귀 촉진 및 기립성 어지럼증 완화",
      tourApiContentId: "C010100_04",
      isMajorRoute: true,
    },
    walkMinutes: 20,
    distanceMeters: 580,
    walkingRoute: [
      [126.9742, 37.5658],
      [126.9748, 37.5660],
      [126.9755, 37.5661],
      [126.9760, 37.5662],
      [126.9765, 37.5662],
    ],
    waypoints: [
      {
        id: "wp-4-1",
        name: "정동극장 안심 화장실 & 휴게홀",
        category: "화장실",
        description: "보행로 중간에 위치한 쾌적한 실내 개방 안심화장실",
        address: "서울특별시 중구 정동길 43",
        latitude: 37.5660,
        longitude: 126.9752,
        walkingMinutesFromRoute: 2,
        distanceMetersFromRoute: 80,
        features: ["장애인 화장실", "비데", "휴게 의자", "온수 공급"],
      },
      {
        id: "wp-4-2",
        name: "돌담길 회복 벤치 쉼터",
        category: "쉼터",
        description: "은행나무 그늘 아래 보행 피로를 풀 수 있는 연속 벤치 구역",
        address: "서울특별시 중구 정동 덕수궁길 일원",
        latitude: 37.5661,
        longitude: 126.9758,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 40,
        features: ["가로수 그늘", "목재 벤치", "음수대"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 정맥혈 순환 유도로 기립성 저혈압 예방 및 활력 회복",
  },
];

// 1박 2일 공식/블로그 검증 장기 웰니스 코스 (한국관광공사 Tour API searchStay2 연계)
export const INITIAL_MULTI_DAY_COURSES: MultiDayCourseSet[] = [
  {
    id: "multi-course-1",
    title: "1박 2일: [당뇨·혈관 케어] 남산 숲속 힐링 & 한옥 안심 스테이",
    duration: "1박 2일",
    targetCondition: "당뇨, 고혈압 (지속적 식단 & 운동 루틴)",
    stay: {
      id: "stay-1",
      name: "나인트리 레지던스 & 안심 스테이 명동",
      address: "서울특별시 중구 명동길 61",
      description: "객실 내 주방에서 저염/저당 건강식을 직접 조리할 수 있고, 인슐린 냉장 보관 및 피트니스 룸을 완비한 웰니스 공인 숙소",
      latitude: 37.5635,
      longitude: 126.9855,
      chkcooking: true,       // 객실 내 취사 가능 (저염식 직접 조리)
      roomrefrigerator: true, // 객실 내 냉장고 보유 (인슐린 의약품 보관)
      fitness: true,          // 피트니스 센터 보유 (식후 혈당 조절 걷기)
      safeBadges: ["🍳 객실 내 취사 가능", "❄️ 인슐린 안심 냉장고", "🏋️ 피트니스 센터 완비"],
      contact: "02-6967-0999",
    },
    days: [
      {
        day: 1,
        title: "1일차: 저당 안심식사 ➔ 남산 소나무길 완보 ➔ 숙소 체크인",
        description: "자연식으로 혈당 스파이크를 방어하고, 완경사 소나무길을 걸어 인슐린 감수성을 극대화합니다.",
        steps: [
          {
            type: "식사",
            name: "소담한 자연밥상 (점심)",
            description: "GI 50 이하 유기농 제철 나물쌈과 찰현미 솥밥",
            tags: ["당류 4g", "나트륨 380mg", "저염인증"],
          },
          {
            type: "산책",
            name: "남산 힐링 소나무 자락길 (오후)",
            description: "경사도 4.5% 미만의 휠체어/시니어 완만 무장애 목재 데크길 (30분)",
            tags: ["완경사 5%미만", "화장실 인접", "그늘쉼터"],
          },
          {
            type: "숙박",
            name: "나인트리 레지던스 체크인 (저녁)",
            description: "인슐린 약물 냉장 보관 후 객실 내 주방에서 안심 식단 조리 및 휴식",
            tags: ["취사 가능", "인슐린 냉장고", "피트니스 센터"],
          },
        ],
      },
      {
        day: 2,
        title: "2일차: 객실 저염 조식 ➔ 용산 호수 둘레길 회복 걷기",
        description: "숙소 피트니스에서 가벼운 스트레칭 후, 평탄한 용산가족공원 호수길을 걸으며 여행을 마무리합니다.",
        steps: [
          {
            type: "체험",
            name: "모닝 스트레칭 & 저염식 (오전)",
            description: "숙소 피트니스 룸에서 가벼운 유산소 및 객실 내 저당 조식",
            tags: ["실내 운동", "혈당 체크", "안심 조리"],
          },
          {
            type: "식사",
            name: "도심속 풀향기 건강식당 (점심)",
            description: "루틴 성분 풍부한 순메밀과 칼륨 배출 맑은 육수 정식",
            tags: ["염도 0.5%이하", "나트륨 310mg"],
          },
          {
            type: "산책",
            name: "용산가족공원 호수 둘레길 (오후)",
            description: "완벽한 평지 흙길과 호수 전망 벤치에서 즐기는 자율신경계 이완 산책 (25분)",
            tags: ["완벽 평지", "호수 뷰", "쉼터 완비"],
          },
        ],
      },
    ],
  },
];

// 헬스케어 지원 안심 숙소 목록 (취사 가능, 인슐린 냉장고, 피트니스 센터)
export const INITIAL_WELLNESS_STAYS: WellnessStay[] = [
  {
    id: "stay-1",
    name: "나인트리 프리미어 레지던스 명동",
    naverPlaceName: "나인트리 프리미어 호텔 명동",
    address: "서울특별시 중구 명동길 61",
    description: "전 객실 주방 완비로 저염식 직접 조리 가능, 인슐린 전용 냉장고 및 24시간 피트니스 센터 보유",
    latitude: 37.5635,
    longitude: 126.9855,
    chkcooking: true,
    roomrefrigerator: true,
    fitness: true,
    safeBadges: ["🍳 객실 취사 완비", "❄️ 인슐린 냉장고", "🏋️ 24h 피트니스"],
    contact: "02-6967-0999",
  },
  {
    id: "stay-2",
    name: "서머셋 팰리스 서울 (종로/인사동)",
    naverPlaceName: "서머셋팰리스 서울",
    address: "서울특별시 종로구 율곡로2길 7",
    description: "주방 조리 시설과 대형 냉장고, 실내 피트니스와 루프탑 산책로를 갖춘 장기 체류형 안심 레지던스",
    latitude: 37.5752,
    longitude: 126.9824,
    chkcooking: true,
    roomrefrigerator: true,
    fitness: true,
    safeBadges: ["🍳 풀옵션 주방", "❄️ 냉동/냉장고", "🏋️ 웰니스 피트니스", "🌿 루프탑 쉼터"],
    contact: "02-6730-8888",
  },
  {
    id: "stay-3",
    name: "남산 힐링 레지던스 스테이",
    naverPlaceName: "서울특별시 중구 퇴계로 18길 32",
    address: "서울특별시 중구 퇴계로 18길 32",
    description: "남산 둘레길 진입로 바로 앞, 독립 주방과 저온 약물 냉장고를 구비한 조용한 숲세권 힐링 숙소",
    latitude: 37.5588,
    longitude: 126.9848,
    chkcooking: true,
    roomrefrigerator: true,
    fitness: false,
    safeBadges: ["🍳 취사 가능", "❄️ 인슐린 냉장고", "🌲 남산 자락 바로 앞"],
    contact: "02-778-5522",
  },
  {
    id: "stay-4",
    name: "그랜드 앰배서더 웰니스 호텔",
    naverPlaceName: "앰배서더 서울 풀만 호텔",
    address: "서울특별시 중구 동호로 287",
    description: "전문 트레이너 상주 메디컬 피트니스와 실내 보행 트랙, 약물 냉장 보관 컨시어지 서비스 제공",
    latitude: 37.5601,
    longitude: 127.0034,
    chkcooking: false,
    roomrefrigerator: true,
    fitness: true,
    safeBadges: ["❄️ 의료 냉장 컨시어지", "🏋️ 메디컬 피트니스", "🏊 저충격 실내 트랙"],
    contact: "02-2275-1101",
  },
];

// 관광명소 연계 웰니스 스탬프 퀘스트 및 칭호 리워드
export const INITIAL_WELLNESS_QUESTS: WellnessQuest[] = [
  {
    id: "quest-1",
    title: "남산 N서울타워 & 솔숲길 30분 안심 완보 퀘스트",
    description: "피톤치드 가득한 남산 소나무 자락길을 30분간 여유롭게 완보하여 식후 혈당을 안정화하세요.",
    landmarkName: "남산 서울타워 & 솔숲길",
    naverPlaceName: "N서울타워",
    category: "산책로/자연",
    address: "서울특별시 중구 남산공원길 105",
    latitude: 37.5512,
    longitude: 126.9882,
    targetDurationMinutes: 30,
    titleReward: "초록빛 혈관 수호자 🏅",
    badgeIcon: "🌲",
    isCompleted: false,
    progressMinutes: 0,
  },
  {
    id: "quest-2",
    title: "덕수궁 돌담길 & 정동 역사문화 20분 힐링 산책",
    description: "식사 후 계단 없는 완벽한 평지 돌담길을 20분간 산책하여 기립성 어지럼증을 예방하고 활력을 충전하세요.",
    landmarkName: "덕수궁 돌담길 & 정동길",
    naverPlaceName: "덕수궁 돌담길",
    category: "역사문화/도심",
    address: "서울특별시 중구 정동 덕수궁길 24",
    latitude: 37.5662,
    longitude: 126.9765,
    targetDurationMinutes: 20,
    titleReward: "도심 속 웰니스 탐험가 🌿",
    badgeIcon: "🏛️",
    isCompleted: false,
    progressMinutes: 0,
  },
  {
    id: "quest-3",
    title: "청계천 무장애 수변길 25분 활력 걷기",
    description: "물소리를 들으며 스트레스를 낮추고 수변 데크길을 25분간 걸어 모세혈관 순환을 촉진합니다.",
    landmarkName: "청계천 수변 산책로",
    naverPlaceName: "청계광장",
    category: "수변/도심",
    address: "서울특별시 중구 태평로1가 청계광장",
    latitude: 37.5691,
    longitude: 126.9786,
    targetDurationMinutes: 25,
    titleReward: "물빛 청량 활력왕 💧",
    badgeIcon: "🌊",
    isCompleted: false,
    progressMinutes: 0,
  },
];

