import { WellnessCourseSet, UserProfile } from "../types/wellness.types";

export const INITIAL_USER_PROFILE: UserProfile = {
  userName: "김건강 님",
  chronicConditions: ["당뇨", "고혈압"],
  allergies: ["갑각류", "땅콩"],
  dietaryPreference: "저염/저탄수화물",
  conditionToday: "식후 30분 가벼운 평지 산책 희망",
  recoloredZones: 1,
};

export const INITIAL_WELLNESS_COURSES: WellnessCourseSet[] = [
  {
    id: "course-1",
    title: "1코스: [당뇨케어] 자연 쌈채 밥상 ➔ 남산 소나무 자락길",
    targetCondition: "당뇨 (급격한 혈당 스파이크 방지)",
    restaurant: {
      id: "rest-1",
      name: "소담한 자연밥상",
      category: "안심식당",
      description: "당 지수(GI) 50 이하 유기농 현미와 제철 저염 나물 요리 전문점",
      address: "서울특별시 중구 소파로 83",
      latitude: 37.5583,
      longitude: 126.9825,
      safeTags: ["GI지수 낮음", "저염식", "친환경채소"],
      healthBenefit: "복합 탄수화물 식단으로 완만한 인슐린 분비 유도",
      tourApiContentId: "FD010100_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-1",
      name: "남산 힐링 소나무 자락길",
      category: "산책로",
      description: "경사도 4.5% 미만의 휠체어/시니어 완만 무장애 목재 데크길",
      address: "서울특별시 중구 회현동 남산공원 자락길",
      latitude: 37.5545,
      longitude: 126.9850,
      safeTags: ["완경사 5%미만", "무장애 데크", "쉼터 완비"],
      healthBenefit: "식후 30분 완보로 근육의 포도당 흡수율 40% 증가",
      tourApiContentId: "C010100_01",
      isMajorRoute: true,
    },
    walkMinutes: 30,
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 최고 혈당 25mg/dL 억제 및 피로 회복",
    questCoupon: {
      name: "남산 로컬 친환경 웰빙 생과일 주스 50% 할인권",
      barcode: "WELLNESS-2026-NAMSAN-8891",
      discountDesc: "남산 힐링 카페 전 메뉴 50% 즉시 할인 (GPS 완주 인증 완료)",
      isCompleted: true,
    },
  },
  {
    id: "course-2",
    title: "2코스: [고혈압케어] 저염 메밀 정식 ➔ 용산가족공원 호수길",
    targetCondition: "고혈압 (나트륨 배출 및 혈관 이완)",
    restaurant: {
      id: "rest-2",
      name: "도심속 풀향기 건강식당",
      category: "안심식당",
      description: "염도 0.5% 이하 안심 인증 식당, 루틴 성분 풍부한 순메밀 요리",
      address: "서울특별시 용산구 이태원로 29",
      latitude: 37.5348,
      longitude: 126.9942,
      safeTags: ["염도 0.5%이하", "칼륨 풍부", "루틴 함유"],
      healthBenefit: "나트륨 배출 및 모세혈관 탄력성 강화",
      tourApiContentId: "FD010200_02",
      isMajorRoute: false,
    },
    trail: {
      id: "trail-2",
      name: "용산가족공원 호수 둘레길",
      category: "산책로",
      description: "호수를 감싸는 평탄한 흙길과 그늘 벤치가 잘 조성된 회복로",
      address: "서울특별시 용산구 서빙고로 185",
      latitude: 37.5242,
      longitude: 126.9805,
      safeTags: ["완벽 평지", "호수 뷰", "넓은 보행로"],
      healthBenefit: "안정된 심박수와 자율신경계 긴장 완화로 혈압 강하",
      tourApiContentId: "C010200_02",
      isMajorRoute: false,
    },
    walkMinutes: 25,
    slopeGrade: "완만(무장애)",
    expectedEffect: "수축기 혈압 8~10mmHg 일시적 하강 효과",
    questCoupon: {
      name: "용산 로컬 웰니스 마켓 5,000원 체험권",
      barcode: "WELLNESS-2026-YONGSAN-4512",
      discountDesc: "용산 로컬 유기농 스낵 5,000원 무료 증정 (현장 인증 시 지급)",
      isCompleted: false,
    },
  },
  {
    id: "course-3",
    title: "3코스: [복합대사케어] 한옥 버섯전골 ➔ 삼청공원 피톤치드 숲길",
    targetCondition: "복합 대사증후군 (체지방 연소 & 면역)",
    restaurant: {
      id: "rest-3",
      name: "한옥 채움 약선당",
      category: "안심식당",
      description: "베타글루칸 풍부한 자연산 버섯 전골과 찰보리 솥밥",
      address: "서울특별시 종로구 북촌로 42",
      latitude: 37.5815,
      longitude: 126.9855,
      safeTags: ["베타글루칸", "무가당", "면역 증진"],
      healthBenefit: "콜레스테롤 개선 및 장내 미생물 균형",
      tourApiContentId: "FD010100_03",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-3",
      name: "삼청공원 숲속 무장애 데크길",
      category: "산책로",
      description: "소나무와 단풍나무 사이로 피톤치드가 뿜어져 나오는 숲길",
      address: "서울특별시 종로구 삼청로 156",
      latitude: 37.5890,
      longitude: 126.9840,
      safeTags: ["숲속 산소", "완만 데크", "피톤치드"],
      healthBenefit: "산소 섭취량 증가 및 림프 순환 활성화",
      tourApiContentId: "C010300_03",
      isMajorRoute: true,
    },
    walkMinutes: 35,
    slopeGrade: "보통",
    expectedEffect: "기초대사량 증진 및 코르티솔(스트레스 호르몬) 30% 감소",
    questCoupon: {
      name: "북촌 전통 한옥 찻집 무가당 수제차 1잔 교환권",
      barcode: "WELLNESS-2026-BUKCHON-9903",
      discountDesc: "북촌 약선 차 1잔 무료 제공 (GPS 인증 시)",
      isCompleted: false,
    },
  },
];
