import {
  WellnessCourseSet,
  UserProfile,
  MultiDayCourseSet,
  WellnessStay,
  WellnessQuest,
} from "../types/wellness.types";

export const INITIAL_USER_PROFILE: UserProfile = {
  userName: "웰니스 여행자",
  chronicConditions: ["당뇨", "고혈압"],
  medications: [
    {
      id: "init-med-1",
      name: "다이아벡스정 500mg",
      ingredientName: "메트포르민염산염",
      timing: "아침 식후",
      cautionNote: "⚠️ 식후 30분 규칙적 완보 권장 / 식사 거름 방지",
      durWarningTags: ["용량주의", "노인주의"],
      inferredCondition: "당뇨",
    },
    {
      id: "init-med-2",
      name: "코자엑스큐정 5/50mg",
      ingredientName: "로사르탄/암로디핀",
      timing: "아침 식후",
      cautionNote: "⚠️ 탈수 주의 / 산책로 화장실 인프라 자동 확보",
      durWarningTags: ["임부금기", "노인주의"],
      inferredCondition: "고혈압",
    },
  ],
  hasNoMedications: false,
  allergies: ["갑각류", "땅콩"],
  dietaryPreference: "저염/저탄수화물",
  conditionToday: "식후 30분 가벼운 평지 산책 희망",
  walkFitnessLevel: "식후 30분 가벼운 평지 산책 희망",
  requiredInfra: ["중간 화장실 필수", "완만한 평지/쉼터 필수"],
};

export const INITIAL_WELLNESS_COURSES: WellnessCourseSet[] = [
  {
    id: "course-1",
    title: "1코스: [당뇨케어] 자연 쌈채 밥상 ➔ 남산 소나무 자락길",
    targetCondition: "당뇨 (급격한 혈당 스파이크 방지)",
    restaurant: {
      id: "rest-1",
      name: "소담한 자연밥상",
      category: "안심식당",
      description: "당 지수(GI) 50 이하 유기농 현미와 제철 저염 나물 요리 전문점",
      address: "서울특별시 중구 소파로 83",
      latitude: 37.5583,
      longitude: 126.9825,
      safeTags: ["GI지수 낮음", "저염식", "친환경채소"],
      healthBenefit: "복합 탄수화물 식단으로 완만한 인슐린 분비 유도",
      nutrition: {
        menuName: "유기농 제철 쌈채 밥상",
        calories: 420,
        carbohydrate: 58,
        sugars: 4,
        sodium: 380,
        protein: 16,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 4g(안심), 나트륨 380mg(안심)의 완벽한 당뇨 케어 식단",
      },
      tourApiContentId: "FD010100_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-1",
      name: "남산 힐링 소나무 자락길",
      category: "산책로",
      description: "경사도 4.5% 미만의 휠체어/시니어 완만 무장애 목재 데크길",
      address: "서울특별시 중구 회현동 남산공원 자락길",
      latitude: 37.5545,
      longitude: 126.9850,
      safeTags: ["완경사 5%미만", "무장애 데크", "쉼터 완비"],
      healthBenefit: "식후 30분 완보로 근육의 포도당 흡수율 40% 증가",
      tourApiContentId: "C010100_01",
      isMajorRoute: true,
    },
    walkMinutes: 41,
    distanceMeters: 1000,
    walkingRoute: [
      [126.9825, 37.5583],   // 소담한 자연밥상 (출발지 마커 완벽 일치)
      [126.9827, 37.55775],  // 소파로 하행
      [126.98305, 37.5571],  // 소파로 삼거리
      [126.98335, 37.55645], // 남산케이블카 매점, 촛불1978 앞
      [126.98315, 37.5558],  // 소파로 커브 진입로
      [126.9827, 37.5554],   // 굽이치는 도로 구간
      [126.9821, 37.55505],  // 서측 굽이길
      [126.9818, 37.5548],   // 첫 번째 헤어핀 U턴 지점 (체육센터 북측)
      [126.98215, 37.5546],  // U턴 회전 구간
      [126.98275, 37.55435], // 소파로 하단 도로
      [126.9831, 37.5541],   // 두 번째 헤어핀 반전 지점
      [126.98345, 37.55435], // 북동향 소월로 연결 보행로 진입
      [126.98365, 37.5547],  // 보행 데크길 입구
      [126.9839, 37.55495],  // 조지훈 시비 남측 연결로
      [126.98425, 37.5548],  // 목멱산방 방향 숲길 보행로
      [126.9845, 37.55455],  // 목멱산방 앞
      [126.98475, 37.5544],  // 소나무 자락길 데크길 초입
      [126.9850, 37.5545],   // 남산 힐링 소나무 자락길 종점 (도착지 마커 완벽 일치)
    ],
    // 이동 동선 중간 도보 3~5분 공공 편의시설 (Tour API detailInfo2 연계)
    waypoints: [
      {
        id: "wp-1-1",
        name: "남산공원 안심 공중화장실",
        category: "화장실",
        description: "고혈압·시니어 보행 약자를 위한 상시 개방형 청결 안심화장실",
        address: "서울특별시 중구 소파로 95",
        latitude: 37.5566,
        longitude: 126.9841,
        walkingMinutesFromRoute: 3,
        distanceMetersFromRoute: 150,
        features: ["장애인 화장실", "비데 완비", "안심 비상벨", "온수 공급"],
      },
      {
        id: "wp-1-2",
        name: "소나무숲 그늘 팔각정 쉼터",
        category: "쉼터",
        description: "피로 누적 시 즉시 휴식할 수 있는 솔숲 그늘 벤치와 정자",
        address: "서울특별시 중구 남산공원 소나무숲길 중턱",
        latitude: 37.5558,
        longitude: 126.9834,
        walkingMinutesFromRoute: 4,
        distanceMetersFromRoute: 190,
        features: ["목재 평상", "그늘 벤치", "음수대", "피톤치드 풍부"],
      },
      {
        id: "wp-1-3",
        name: "남산 무장애 경사로 & 쉼터",
        category: "배리어프리",
        description: "휠체어 및 보행 보조기 이용자를 위한 단차 없는 완경사 데크",
        address: "서울특별시 중구 회현동1가 산1-16",
        latitude: 37.5572,
        longitude: 126.9832,
        walkingMinutesFromRoute: 5,
        distanceMetersFromRoute: 240,
        features: ["경사도 3.8% 완경사", "점자 유도블록", "휠체어 쉼터"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 최고 혈당 25mg/dL 억제 및 피로 회복",
    region: "서울 도심",
    isLocal: false,
  },
  {
    id: "course-2",
    title: "2코스: [고혈압케어] 저염 메밀 정식 ➔ 용산가족공원 호수길",
    targetCondition: "고혈압 (나트륨 배출 및 혈관 이완)",
    restaurant: {
      id: "rest-2",
      name: "이촌 풀향기 메밀정식",
      naverPlaceName: "서울특별시 용산구 이촌로 319",
      category: "안심식당",
      description: "염도 0.5% 이하 안심 인증 식당, 루틴 성분 풍부한 순메밀 요리",
      address: "서울특별시 용산구 이촌로 319",
      latitude: 37.5235,
      longitude: 126.9745,
      safeTags: ["염도 0.5%이하", "칼륨 풍부", "루틴 함유"],
      healthBenefit: "나트륨 배출 및 모세혈관 탄력성 강화",
      nutrition: {
        menuName: "메밀 순면 맑은 정식",
        calories: 460,
        carbohydrate: 64,
        sugars: 3,
        sodium: 310,
        protein: 14,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 나트륨 310mg(안심)으로 일반 외식(1,200mg) 대비 74% 나트륨 저감",
      },
      tourApiContentId: "FD010200_02",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-2",
      name: "용산가족공원 호수 둘레길",
      naverPlaceName: "용산가족공원",
      category: "산책로",
      description: "호수를 감싸는 평탄한 흙길과 그늘 벤치가 잘 조성된 회복로",
      address: "서울특별시 용산구 서빙고로 185",
      latitude: 37.5242,
      longitude: 126.9805,
      safeTags: ["완벽 평지", "호수 뷰", "넓은 보행로"],
      healthBenefit: "안정된 심박수와 자율신경계 긴장 완화로 혈압 강하",
      tourApiContentId: "C010200_02",
      isMajorRoute: true,
    },
    walkMinutes: 9,
    distanceMeters: 620,
    walkingRoute: [
      [126.9745, 37.5235],
      [126.9760, 37.5238],
      [126.9775, 37.5240],
      [126.9790, 37.5241],
      [126.9805, 37.5242],
    ],
    waypoints: [
      {
        id: "wp-2-1",
        name: "용산가족공원 입구 청결화장실",
        category: "화장실",
        description: "이뇨제 복용 환자가 급히 찾을 수 있는 넓은 다목적 공중화장실",
        address: "서울특별시 용산구 서빙고로 185 잔디광장 앞",
        latitude: 37.5241,
        longitude: 126.9785,
        walkingMinutesFromRoute: 2,
        distanceMetersFromRoute: 70,
        features: ["장애인 화장실", "냉난방 완비", "기저귀 교환대", "자동 손세정"],
      },
      {
        id: "wp-2-2",
        name: "호수변 버드나무 그늘 벤치 쉼터",
        category: "쉼터",
        description: "물소리를 들으며 혈압과 심박수를 안정시킬 수 있는 평탄 쉼터",
        address: "서울특별시 용산구 서빙고동 호수둘레길 2지점",
        latitude: 37.5243,
        longitude: 126.9798,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 40,
        features: ["호수 전망 벤치", "그늘막", "자동 혈압계 비치"],
      },
      {
        id: "wp-2-3",
        name: "국립중앙박물관 무장애 평지 통로",
        category: "배리어프리",
        description: "계단 없이 평지만으로 공원과 박물관을 잇는 안전 보행로",
        address: "서울특별시 용산구 서빙고로 137 연결통로",
        latitude: 37.5238,
        longitude: 126.9768,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 50,
        features: ["전동휠체어 급속충전기", "단차 제로 평지", "야간 안심조명"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "수축기 혈압 8~10mmHg 일시적 하강 효과",
    region: "서울 도심",
    isLocal: false,
  },
  {
    id: "course-3",
    title: "3코스: [복합대사케어] 한옥 버섯전골 ➔ 삼청공원 피톤치드 숲길",
    targetCondition: "복합 대사증후군 (체지방 연소 & 면역)",
    restaurant: {
      id: "rest-3",
      name: "한옥 채움 약선당",
      category: "안심식당",
      description: "베타글루칸 풍부한 자연산 버섯 전골과 찰보리 솥밥",
      address: "서울특별시 종로구 북촌로 42",
      latitude: 37.5815,
      longitude: 126.9855,
      safeTags: ["베타글루칸", "무가당", "면역 증진"],
      healthBenefit: "콜레스테롤 개선 및 장내 미생물 균형",
      nutrition: {
        menuName: "자연산 모둠 버섯전골",
        calories: 440,
        carbohydrate: 52,
        sugars: 5,
        sodium: 420,
        protein: 20,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 식이섬유 12g, 당류 5g(안심)으로 인슐린 저항성 완화",
      },
      tourApiContentId: "FD010100_03",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-3",
      name: "삼청공원 숲속 무장애 데크길",
      category: "산책로",
      description: "소나무와 단풍나무 사이로 피톤치드가 뿜어져 나오는 숲길",
      address: "서울특별시 종로구 삼청로 156",
      latitude: 37.5890,
      longitude: 126.9840,
      safeTags: ["숲속 산소", "완만 데크", "피톤치드"],
      healthBenefit: "산소 섭취량 증가 및 림프 순환 활성화",
      tourApiContentId: "C010300_03",
      isMajorRoute: true,
    },
    walkMinutes: 35,
    distanceMeters: 920,
    walkingRoute: [
      [126.9855, 37.5815],
      [126.9852, 37.5830],
      [126.9848, 37.5850],
      [126.9845, 37.5870],
      [126.9840, 37.5890],
    ],
    waypoints: [
      {
        id: "wp-3-1",
        name: "삼청공원 숲속 안심화장실",
        category: "화장실",
        description: "공원 입구에 위치한 장애물 없는 청결 안심화장실",
        address: "서울특별시 종로구 북촌로 137 삼청공원 입구",
        latitude: 37.5872,
        longitude: 126.9842,
        walkingMinutesFromRoute: 3,
        distanceMetersFromRoute: 160,
        features: ["장애인 화장실", "안심 비상벨", "온수 공급", "24시간 개방"],
      },
      {
        id: "wp-3-2",
        name: "피톤치드 소나무 정자 쉼터",
        category: "쉼터",
        description: "삼청동 전경을 조망하며 쉴 수 있는 힐링 마루 쉼터",
        address: "서울특별시 종로구 삼청동 삼청공원 둘레길",
        latitude: 37.5855,
        longitude: 126.9850,
        walkingMinutesFromRoute: 4,
        distanceMetersFromRoute: 200,
        features: ["목재 정자", "그늘막 벤치", "숲속 산소 쉼터"],
      },
      {
        id: "wp-3-3",
        name: "북촌 전통문화 무장애 쉼터",
        category: "배리어프리",
        description: "전통 한옥 양식으로 지어진 보행 약자 휴게 쉼터",
        address: "서울특별시 종로구 계동길 37",
        latitude: 37.5832,
        longitude: 126.9858,
        walkingMinutesFromRoute: 4,
        distanceMetersFromRoute: 180,
        features: ["단차 없는 출입구", "안내 점자", "휴식 다도 쉼터"],
      },
    ],
    slopeGrade: "보통",
    expectedEffect: "기초대사량 증진 및 코르티솔(스트레스 호르몬) 30% 감소",
    region: "서울 도심",
    isLocal: false,
  },
  {
    id: "course-4",
    title: "4코스: [저혈압케어] 고단백 영양 솥밥 ➔ 덕수궁 돌담길 평지 산책",
    targetCondition: "저혈압 (식후 저혈압·어지럼증 방지 식후 필수 산책)",
    restaurant: {
      id: "rest-4",
      name: "정동 온반 건강 솥밥",
      category: "안심식당",
      description: "양질의 단백질과 미네랄이 풍부한 영양 전복 솥밥과 따뜻한 건강 온반",
      address: "서울특별시 중구 정동길 12",
      latitude: 37.5658,
      longitude: 126.9742,
      safeTags: ["고단백", "적정 미네랄", "온기 보양"],
      healthBenefit: "식후 소화 흡수 촉진 및 혈액 순환 개선",
      nutrition: {
        menuName: "영양 전복 버섯 솥밥 정식",
        calories: 480,
        carbohydrate: 62,
        sugars: 3,
        sodium: 490,
        protein: 24,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 단백질 24g, 적정 나트륨 490mg(안심)으로 식후 혈압 급강하 방지",
      },
      tourApiContentId: "FD010100_04",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-4",
      name: "덕수궁 돌담길 평지 산책로",
      category: "산책로",
      description: "식당 바로 앞 계단 없는 100% 완전 평지 보행로 (식후 20분 완보로 하지 혈액 순환 촉진)",
      address: "서울특별시 중구 정동 덕수궁길 24",
      latitude: 37.5662,
      longitude: 126.9765,
      safeTags: ["완전 평지 0%", "보행 전용길", "가로수 그늘"],
      healthBenefit: "종아리 근육 펌핑을 통해 심장으로의 정맥혈 회귀 촉진 및 기립성 어지럼증 완화",
      tourApiContentId: "C010100_04",
      isMajorRoute: true,
    },
    walkMinutes: 20,
    distanceMeters: 580,
    walkingRoute: [
      [126.9742, 37.5658],
      [126.9748, 37.5660],
      [126.9755, 37.5661],
      [126.9760, 37.5662],
      [126.9765, 37.5662],
    ],
    waypoints: [
      {
        id: "wp-4-1",
        name: "정동극장 안심 화장실 & 휴게홀",
        category: "화장실",
        description: "보행로 중간에 위치한 쾌적한 실내 개방 안심화장실",
        address: "서울특별시 중구 정동길 43",
        latitude: 37.5660,
        longitude: 126.9752,
        walkingMinutesFromRoute: 2,
        distanceMetersFromRoute: 80,
        features: ["장애인 화장실", "비데", "휴게 의자", "온수 공급"],
      },
      {
        id: "wp-4-2",
        name: "돌담길 회복 벤치 쉼터",
        category: "쉼터",
        description: "은행나무 그늘 아래 보행 피로를 풀 수 있는 연속 벤치 구역",
        address: "서울특별시 중구 정동 덕수궁길 일원",
        latitude: 37.5661,
        longitude: 126.9758,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 40,
        features: ["가로수 그늘", "목재 벤치", "음수대"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 정맥혈 순환 유도로 기립성 저혈압 예방 및 활력 회복",
    region: "서울 도심",
    isLocal: false,
  },
  {
    id: "course-ansan-1",
    title: "안산 1코스: [당뇨케어] 단원 쌈채 자연밥상 ➔ 화랑유원지 수변 둘레길",
    targetCondition: "당뇨 (급격한 혈당 스파이크 방지)",
    region: "안산/경기남부",
    isLocal: true,
    restaurant: {
      id: "rest-ansan-1",
      name: "단원 쌈채 자연밥상 (화랑점)",
      naverPlaceName: "경기도 안산시 단원구 동산로 268",
      category: "안심식당",
      description: "유기농 쌈채소와 저염 우렁강된장, 혈당 조절 찰보리 솥밥 전문점",
      address: "경기도 안산시 단원구 동산로 268",
      latitude: 37.3275,
      longitude: 126.8145,
      safeTags: ["GI지수 낮음", "저염 우렁쌈", "친환경채소"],
      healthBenefit: "풍부한 식이섬유로 장내 포도당 흡수 속도 지연",
      nutrition: {
        menuName: "우렁 쌈채 제철 솥밥",
        calories: 430,
        carbohydrate: 56,
        sugars: 4,
        sodium: 390,
        protein: 17,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 4g(안심), 나트륨 390mg(안심)의 완벽한 혈당 방어 식단",
      },
      tourApiContentId: "FD_ANSAN_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-ansan-1",
      name: "안산 화랑유원지 수변 둘레길",
      naverPlaceName: "화랑유원지",
      category: "산책로",
      description: "호수를 둘러싼 100% 완전 평지 목재 데크로드와 울창한 가로수 그늘길",
      address: "경기도 안산시 단원구 동산로 268 화랑유원지",
      latitude: 37.324,
      longitude: 126.8185,
      safeTags: ["완전 평지 0%", "수변 데크", "그늘 쉼터"],
      healthBenefit: "식후 20분 완보로 근육의 포도당 소모 촉진",
      tourApiContentId: "C_ANSAN_01",
      isMajorRoute: true,
    },
    walkMinutes: 18,
    distanceMeters: 850,
    walkingRoute: [
      [126.8145, 37.3275],
      [126.8152, 37.3282],
      [126.8163, 37.3286],
      [126.8176, 37.3284],
      [126.8186, 37.3275],
      [126.8191, 37.3262],
      [126.8190, 37.3250],
      [126.8185, 37.3240],
    ],
    waypoints: [
      {
        id: "wp-a-1",
        name: "화랑유원지 안심 공중화장실",
        category: "화장실",
        description: "호수 둘레길 산책로 초입 청결 안심화장실",
        address: "경기도 안산시 단원구 동산로 268",
        latitude: 37.326,
        longitude: 126.8168,
        walkingMinutesFromRoute: 2,
        distanceMetersFromRoute: 60,
        features: ["장애인 화장실", "비상벨", "온수"],
      },
      {
        id: "wp-a-2",
        name: "화랑호수 버드나무 그늘 쉼터",
        category: "쉼터",
        description: "호수 바람을 맞으며 혈당을 안정시키는 수변 벤치",
        address: "경기도 안산시 단원구 초지동 667",
        latitude: 37.3248,
        longitude: 126.8178,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 30,
        features: ["수변 전망", "그늘막 벤치", "평탄 쉼터"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 혈당 스파이크 30mg/dL 완화 및 피로 회복",
  },
  {
    id: "course-ansan-2",
    title: "안산 2코스: [고혈압케어] 고잔 순메밀 맑은정식 ➔ 안산호수공원 수변 완만길",
    targetCondition: "고혈압 (나트륨 배출 및 혈관 이완)",
    region: "안산/경기남부",
    isLocal: true,
    restaurant: {
      id: "rest-ansan-2",
      name: "고잔 순메밀 맑은마당",
      naverPlaceName: "경기도 안산시 단원구 광덕대로 155",
      category: "안심식당",
      description: "염도 0.5% 이하 순메밀국수와 칼륨이 풍부한 봄나물 맑은전",
      address: "경기도 안산시 단원구 광덕대로 155",
      latitude: 37.3085,
      longitude: 126.8285,
      safeTags: ["염도 0.5%이하", "칼륨 풍부", "루틴 함유"],
      healthBenefit: "혈관 탄력 개선 및 나트륨 배출 유도",
      nutrition: {
        menuName: "메밀 순면 맑은정식",
        calories: 450,
        carbohydrate: 65,
        sugars: 3,
        sodium: 320,
        protein: 14,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 나트륨 320mg(안심)으로 고혈압 환자 안심",
      },
      tourApiContentId: "FD_ANSAN_02",
      isMajorRoute: false,
    },
    trail: {
      id: "trail-ansan-2",
      name: "안산 호수공원 수변 힐링로",
      naverPlaceName: "안산호수공원",
      category: "산책로",
      description: "갈대와 호수가 어우러진 넓고 평탄한 보행 전용로",
      address: "경기도 안산시 상록구 해봉로 32 안산호수공원",
      latitude: 37.3015,
      longitude: 126.831,
      safeTags: ["완전 평지", "호수 뷰", "넓은 보행로"],
      healthBenefit: "안정된 심박수와 자율신경계 이완으로 혈압 강하",
      tourApiContentId: "C_ANSAN_02",
      isMajorRoute: false,
    },
    walkMinutes: 22,
    distanceMeters: 1100,
    walkingRoute: [
      [126.8285, 37.3085],
      [126.8292, 37.306],
      [126.83, 37.3038],
      [126.831, 37.3015],
    ],
    waypoints: [
      {
        id: "wp-a-3",
        name: "호수공원 중앙광장 안심화장실",
        category: "화장실",
        description: "공원 중앙 광장에 위치한 장애물 없는 청결 화장실",
        address: "경기도 안산시 상록구 해봉로 32",
        latitude: 37.3045,
        longitude: 126.8298,
        walkingMinutesFromRoute: 2,
        distanceMetersFromRoute: 80,
        features: ["장애인 화장실", "비상벨", "냉난방"],
      },
      {
        id: "wp-a-4",
        name: "안산호수 갈대 바람 쉼터",
        category: "쉼터",
        description: "호수 전경을 바라보며 심박수를 안정시키는 평탄 벤치",
        address: "경기도 안산시 상록구 사동 안산호수공원",
        latitude: 37.3025,
        longitude: 126.8305,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 40,
        features: ["갈대숲 뷰", "목재 평상", "음수대"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "수축기 혈압 8mmHg 일시적 하강 및 심신 안정",
  },
  {
    id: "course-ansan-3",
    title: "안산 3코스: [저혈압케어] 성포 영양 전복솥밥 ➔ 노적봉공원 장미원 평지 산책",
    targetCondition: "저혈압 (식후 저혈압·어지럼증 방지 식후 필수 산책)",
    region: "안산/경기남부",
    isLocal: true,
    restaurant: {
      id: "rest-ansan-3",
      name: "성포 온기 영양솥밥",
      naverPlaceName: "경기도 안산시 상록구 충장로 611",
      category: "안심식당",
      description: "단백질과 미네랄이 풍부한 활전복 솥밥과 따뜻한 건강 맑은탕",
      address: "경기도 안산시 상록구 충장로 611",
      latitude: 37.3305,
      longitude: 126.851,
      safeTags: ["고단백", "적정 미네랄", "온기 보양"],
      healthBenefit: "식후 혈액 순환 개선 및 기립성 어지럼증 완화",
      nutrition: {
        menuName: "영양 전복 영양솥밥",
        calories: 470,
        carbohydrate: 60,
        sugars: 3,
        sodium: 480,
        protein: 23,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 단백질 23g, 적정 나트륨 480mg(안심)으로 식후 저혈압 방지",
      },
      tourApiContentId: "FD_ANSAN_03",
      isMajorRoute: false,
    },
    trail: {
      id: "trail-ansan-3",
      name: "노적봉공원 장미원 & 인공폭포 평지길",
      naverPlaceName: "노적봉인공폭포공원",
      category: "산책로",
      description: "식당 바로 앞 완벽한 평지 장미원 둘레길 (식후 15분 완보로 하지 혈액 순환 촉진)",
      address: "경기도 안산시 상록구 성포동 산39-1",
      latitude: 37.3325,
      longitude: 126.854,
      safeTags: ["완전 평지 0%", "폭포 뷰", "장미원 산책로"],
      healthBenefit: "종아리 근육 펌핑으로 정맥혈 순환 촉진 및 어지럼증 예방",
      tourApiContentId: "C_ANSAN_03",
      isMajorRoute: false,
    },
    walkMinutes: 16,
    distanceMeters: 780,
    walkingRoute: [
      [126.851, 37.3305],
      [126.852, 37.3312],
      [126.853, 37.3318],
      [126.854, 37.3325],
    ],
    waypoints: [
      {
        id: "wp-a-5",
        name: "노적봉공원 입구 안심화장실",
        category: "화장실",
        description: "폭포 광장 앞 상시 개방 청결 화장실",
        address: "경기도 안산시 상록구 성포동 산39-1",
        latitude: 37.3315,
        longitude: 126.8525,
        walkingMinutesFromRoute: 2,
        distanceMetersFromRoute: 70,
        features: ["장애인 화장실", "비상벨"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "정맥혈 순환 유도로 기립성 저혈압 예방 및 활력 회복",
  },
  {
    id: "course-ansan-4",
    title: "안산 4코스: [당뇨·고혈압케어] 선부 보약 쌈밥 ➔ 샛터공원 & 선부광장 완만 둘레길",
    targetCondition: "당뇨, 고혈압 (식후 혈당 강하 & 완만 유산소)",
    region: "안산/경기남부",
    isLocal: true,
    restaurant: {
      id: "rest-ansan-4",
      name: "선부 보약 쌈밥 (달미역점)",
      naverPlaceName: "경기도 안산시 단원구 석수로 120",
      category: "안심식당",
      description: "당뇨/고혈압 안심 인증 식당, 12가지 유기농 제철 쌈채소와 저염 우렁강된장 솥밥",
      address: "경기도 안산시 단원구 석수로 120",
      latitude: 37.3445,
      longitude: 126.8140,
      safeTags: ["저염 우렁쌈", "식이섬유 풍부", "당뇨/고혈압 안심"],
      healthBenefit: "식후 급격한 혈당 스파이크 방지 및 풍부한 칼륨으로 나트륨 배출",
      nutrition: {
        menuName: "유기농 우렁 쌈밥 정식",
        calories: 430,
        carbohydrate: 55,
        sugars: 3,
        sodium: 360,
        protein: 18,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 3g, 나트륨 360mg의 완벽한 웰니스 식단",
      },
      tourApiContentId: "FD_ANSAN_04",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-ansan-4",
      name: "선부 샛터공원 & 선부광장 둘레길",
      naverPlaceName: "샛터공원",
      category: "산책로",
      description: "달미역 앞 계단 없는 100% 완전 평지 목재 데크와 울창한 가로수 그늘길 (도보 15분 완보)",
      address: "경기도 안산시 단원구 선부동 1084",
      latitude: 37.3425,
      longitude: 126.8125,
      safeTags: ["완전 평지 0%", "무장애 데크", "달미역 인접"],
      healthBenefit: "식후 20분 완보로 근육의 포도당 소모 및 혈류 순환 촉진",
      tourApiContentId: "C_ANSAN_04",
      isMajorRoute: true,
    },
    walkMinutes: 15,
    distanceMeters: 520,
    walkingRoute: [
      [126.8140, 37.3445],
      [126.8135, 37.3438],
      [126.8130, 37.3432],
      [126.8125, 37.3425],
    ],
    waypoints: [
      {
        id: "wp-a-6",
        name: "선부 샛터공원 안심화장실",
        category: "화장실",
        description: "공원 초입에 위치한 장애인 겸용 청결 화장실",
        address: "경기도 안산시 단원구 선부동 1084",
        latitude: 37.3438,
        longitude: 126.8135,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 30,
        features: ["장애인 화장실", "온수 공급", "비상벨"],
      },
      {
        id: "wp-a-7",
        name: "달미 숲속 힐링 벤치 쉼터",
        category: "쉼터",
        description: "녹음 속에서 심박수와 혈압을 안정시키는 그늘 쉼터",
        address: "경기도 안산시 단원구 선부동 샛터공원 산책로",
        latitude: 37.3430,
        longitude: 126.8128,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 20,
        features: ["그늘막 벤치", "평탄 쉼터"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 최고 혈당 28mg/dL 완화 및 혈류 개선",
  },
  {
    id: "course-goyang-1",
    title: "고양 1코스: [당뇨·고혈압케어] 일산 보약 곤드레 솥밥 ➔ 일산호수공원 무장애 수변길",
    targetCondition: "당뇨, 고혈압 (저GI 식단 & 수변 평지 완보)",
    region: "고양/경기북부",
    isLocal: true,
    restaurant: {
      id: "rest-goyang-1",
      name: "일산 보약 곤드레 솥밥 (정발산점)",
      naverPlaceName: "경기도 고양시 일산동구 정발산로 24",
      category: "안심식당",
      description: "고양시 안심식당 인증, 유기농 곤드레나물과 혈당 조절 귀리 솥밥, 저염 버섯 강된장",
      address: "경기도 고양시 일산동구 정발산로 24",
      latitude: 37.6583,
      longitude: 126.7642,
      safeTags: ["저GI 식단", "저염 강된장", "식이섬유 풍부"],
      healthBenefit: "장내 당 흡수 지연 및 식후 혈당 급상승 방지",
      nutrition: {
        menuName: "제철 곤드레 가마솥밥 정식",
        calories: 410,
        carbohydrate: 54,
        sugars: 3,
        sodium: 350,
        protein: 16,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 3g, 나트륨 350mg의 완벽한 웰니스 식단",
      },
      tourApiContentId: "FD_GOYANG_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-goyang-1",
      name: "일산호수공원 무장애 수변 둘레길",
      naverPlaceName: "일산호수공원",
      category: "산책로",
      description: "국내 최대 인공호수를 둘러싼 완전 평지(0%) 무장애 산책로와 메타세쿼이아 숲길",
      address: "경기도 고양시 일산동구 호수로 595",
      latitude: 37.6545,
      longitude: 126.7680,
      safeTags: ["완전 평지 0%", "수변 힐링", "풍부한 벤치"],
      healthBenefit: "식후 25분 보행으로 인슐린 저항성 완화 및 혈압 강하",
      tourApiContentId: "C_GOYANG_01",
      isMajorRoute: true,
    },
    walkMinutes: 20,
    distanceMeters: 750,
    walkingRoute: [
      [126.7642, 37.6583],
      [126.7655, 37.6570],
      [126.7668, 37.6558],
      [126.7680, 37.6545],
    ],
    waypoints: [
      {
        id: "wp-g-1",
        name: "호수공원 안심 화장실 3호",
        category: "화장실",
        description: "산책로 초입 청결 안심화장실",
        address: "경기도 고양시 일산동구 호수로 595",
        latitude: 37.6565,
        longitude: 126.7660,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 30,
        features: ["장애인 화장실", "비상벨"],
      },
      {
        id: "wp-g-2",
        name: "메타세쿼이아 그늘 쉼터",
        category: "쉼터",
        description: "호수 바람을 맞으며 혈압을 안정시키는 평탄 벤치 구역",
        address: "일산호수공원 수변 산책로",
        latitude: 37.6550,
        longitude: 126.7672,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 20,
        features: ["가로수 그늘", "목재 벤치"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 최고 혈당 30mg/dL 완화",
  },
  {
    id: "course-goyang-2",
    title: "고양 2코스: [저염·혈관케어] 행주 나루터 약선 메밀 ➔ 행주산성 역사누리 평지길",
    targetCondition: "고혈압, 이상지질혈증 (나트륨 배출 & 혈관 탄력)",
    region: "고양/경기북부",
    isLocal: true,
    restaurant: {
      id: "rest-goyang-2",
      name: "행주 나루터 약선 메밀 (본점)",
      naverPlaceName: "경기도 고양시 덕양구 행주로15번길",
      category: "안심식당",
      description: "염도 0.5% 이하 기준 순메밀 국수와 루틴 성분이 풍부한 봄나물 맑은 정식",
      address: "경기도 고양시 덕양구 행주로15번길 45",
      latitude: 37.5960,
      longitude: 126.8180,
      safeTags: ["염도 0.5% 이하", "루틴 풍부", "칼륨 식단"],
      healthBenefit: "모세혈관 강화 및 체내 나트륨 배출 촉진",
      nutrition: {
        menuName: "순메밀 맑은 온면 정식",
        calories: 390,
        carbohydrate: 52,
        sugars: 2,
        sodium: 320,
        protein: 15,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 나트륨 320mg, 당류 2g 고혈압 안심 식단",
      },
      tourApiContentId: "FD_GOYANG_02",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-goyang-2",
      name: "행주산성 역사누리 평지 둘레길",
      naverPlaceName: "행주산성 역사공원",
      category: "산책로",
      description: "한강 하구를 조망하는 완만한 평지 데크로드와 그늘 쉼터",
      address: "경기도 고양시 덕양구 행주외동 한강변",
      latitude: 37.5925,
      longitude: 126.8220,
      safeTags: ["완만 평지", "한강 조망", "무장애 데크"],
      healthBenefit: "안정적인 유산소 보행으로 혈압 강하 유도",
      tourApiContentId: "C_GOYANG_02",
      isMajorRoute: true,
    },
    walkMinutes: 18,
    distanceMeters: 680,
    walkingRoute: [
      [126.8180, 37.5960],
      [126.8195, 37.5945],
      [126.8210, 37.5932],
      [126.8220, 37.5925],
    ],
    waypoints: [
      {
        id: "wp-g-3",
        name: "행주역사공원 수변 화장실",
        category: "화장실",
        description: "한강변 쾌적 안심 공중화장실",
        address: "경기도 고양시 덕양구 행주외동",
        latitude: 37.5935,
        longitude: 126.8205,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 40,
        features: ["장애인 화장실", "온수"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "수축기 혈압 8mmHg 안정화",
  },
  {
    id: "course-suwon-1",
    title: "수원 1코스: [고혈압·이상지질케어] 광교 웰빙 산채정식 ➔ 광교호수공원 수변 데크길",
    targetCondition: "고혈압, 이상지질혈증 (혈류 순환 & 저염식단)",
    region: "수원/경기남부",
    isLocal: true,
    restaurant: {
      id: "rest-suwon-1",
      name: "광교 웰빙 산채정식 (호수공원점)",
      naverPlaceName: "경기도 수원시 영통구 광교호수공원로 80",
      category: "안심식당",
      description: "수원시 안심식당 인증, 들기름으로 맛을 낸 저염 산나물 솥밥과 천연 발효 된장국",
      address: "경기도 수원시 영통구 광교호수공원로 80",
      latitude: 37.2845,
      longitude: 127.0620,
      safeTags: ["저염인증", "오메가3 풍부", "친환경 나물"],
      healthBenefit: "혈중 중성지방 감소 및 혈압 안정",
      nutrition: {
        menuName: "유기농 산채 솥밥 정식",
        calories: 420,
        carbohydrate: 55,
        sugars: 3,
        sodium: 340,
        protein: 17,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 3g, 나트륨 340mg",
      },
      tourApiContentId: "FD_SUWON_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-suwon-1",
      name: "광교호수공원 수변 어반레비 둘레길",
      naverPlaceName: "광교호수공원",
      category: "산책로",
      description: "호수 수면을 걷는 100% 완전 평지 목재 데크로드와 야간 힐링 조명길",
      address: "경기도 수원시 영통구 하동 광교호수공원",
      latitude: 37.2815,
      longitude: 127.0655,
      safeTags: ["완전 평지 0%", "수변 데크", "야간 조명"],
      healthBenefit: "식후 25분 보행으로 인슐린 감수성 극대화",
      tourApiContentId: "C_SUWON_01",
      isMajorRoute: true,
    },
    walkMinutes: 20,
    distanceMeters: 820,
    waypoints: [
      {
        id: "wp-sw-1",
        name: "광교 어반레비 스마트 안심화장실",
        category: "화장실",
        description: "수변 산책로 중간에 위치한 비상벨 구비 화장실",
        address: "광교호수공원 수변로",
        latitude: 37.2830,
        longitude: 127.0635,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 30,
        features: ["장애인 화장실", "비상벨", "냉난방"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "혈관 탄력 개선 및 심폐 활력 증진",
  },
  {
    id: "course-seongnam-1",
    title: "성남 1코스: [당뇨케어] 율동 저당 가마솥 두부마을 ➔ 율동공원 호수 둘레길",
    targetCondition: "당뇨 (고단백 저당 & 식후 완만 완보)",
    region: "성남/분당",
    isLocal: true,
    restaurant: {
      id: "rest-seongnam-1",
      name: "율동 저당 가마솥 두부마을",
      naverPlaceName: "경기도 성남시 분당구 문정로 140",
      category: "안심식당",
      description: "국산 파주 장단콩 100% 전통 손두부와 저염 버섯 전골 전문 안심식당",
      address: "경기도 성남시 분당구 문정로 140",
      latitude: 37.3780,
      longitude: 127.1480,
      safeTags: ["고단백 저탄수", "저염 전골", "국산콩"],
      healthBenefit: "식물성 단백질 공급으로 급격한 식후 혈당 스파이크 차단",
      nutrition: {
        menuName: "가마솥 순두부 곤약 정식",
        calories: 380,
        carbohydrate: 45,
        sugars: 2,
        sodium: 330,
        protein: 22,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 2g, 단백질 22g",
      },
      tourApiContentId: "FD_SEONGNAM_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-seongnam-1",
      name: "성남 율동공원 호수 완만 둘레길",
      naverPlaceName: "율동공원",
      category: "산책로",
      description: "호수 둘레 2.5km 전 구간 무단차 평지 산책로와 번지점프대 잔디 쉼터",
      address: "경기도 성남시 분당구 율동 310",
      latitude: 37.3755,
      longitude: 127.1510,
      safeTags: ["완전 평지", "호수 숲길", "잔디 쉼터"],
      healthBenefit: "관절 무리 없는 유산소 대사 촉진",
      tourApiContentId: "C_SEONGNAM_01",
      isMajorRoute: true,
    },
    walkMinutes: 16,
    distanceMeters: 620,
    waypoints: [
      {
        id: "wp-sn-1",
        name: "율동공원 관리사무소 안심화장실",
        category: "화장실",
        description: "공원 중앙 청결 화장실",
        address: "경기도 성남시 분당구 율동 310",
        latitude: 37.3765,
        longitude: 127.1495,
        walkingMinutesFromRoute: 1,
        distanceMetersFromRoute: 30,
        features: ["장애인 화장실", "음수대"],
      },
    ],
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 1시간 혈당 35mg/dL 감소",
  },
  {
    id: "course-incheon-1",
    title: "인천 1코스: [고혈압·이상지질케어] 송도 약선 메밀정식 ➔ 센트럴파크 해수공원길",
    targetCondition: "고혈압, 이상지질혈증 (나트륨 배출 & 해풍 유산소)",
    region: "인천/수도권서부",
    isLocal: true,
    restaurant: {
      id: "rest-incheon-1",
      name: "송도 약선 메밀정식 (센트럴파크점)",
      naverPlaceName: "인천광역시 연수구 컨벤시아대로 160",
      category: "안심식당",
      description: "인천시 안심식당 인증, 순메밀 100% 온면과 루틴이 풍부한 나물밥상",
      address: "인천광역시 연수구 컨벤시아대로 160",
      latitude: 37.3940,
      longitude: 126.6350,
      safeTags: ["루틴 풍부", "저염식단", "식이섬유"],
      healthBenefit: "모세혈관 탄력 강화 및 혈압 강하 유도",
      nutrition: {
        menuName: "순메밀 온면 정식",
        calories: 395,
        carbohydrate: 53,
        sugars: 2,
        sodium: 330,
        protein: 16,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 2g, 나트륨 330mg 안심 식단",
      },
      tourApiContentId: "FD_INCHEON_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-incheon-1",
      name: "송도 센트럴파크 해수공원 수변 산책로",
      naverPlaceName: "송도센트럴파크",
      category: "산책로",
      description: "국내 최초 해수공원의 100% 완전 평지 보행로와 그늘 쉼터",
      address: "인천광역시 연수구 테크노파크로 196",
      latitude: 37.3910,
      longitude: 126.6380,
      safeTags: ["완전 평지 0%", "해수 수변길", "무장애 산책로"],
      healthBenefit: "식후 25분 완보로 심폐 활력 및 혈류 개선",
      tourApiContentId: "C_INCHEON_01",
      isMajorRoute: true,
    },
    walkMinutes: 20,
    distanceMeters: 780,
    slopeGrade: "완만(무장애)",
    expectedEffect: "수축기 혈압 8mmHg 완화",
  },
  {
    id: "course-daejeon-1",
    title: "대전 1코스: [당뇨·고혈압케어] 둔산 자연채움 보약밥상 ➔ 한밭수목원 평지 숲길",
    targetCondition: "당뇨, 고혈압 (저GI 식단 & 수목원 피톤치드)",
    region: "대전/충청권",
    isLocal: true,
    restaurant: {
      id: "rest-daejeon-1",
      name: "둔산 자연채움 보약밥상 (본점)",
      naverPlaceName: "대전광역시 서구 둔산대로 117",
      category: "안심식당",
      description: "대전시 안심식당 인증, 유기농 찰보리 솥밥과 저염 버섯 우렁된장찌개",
      address: "대전광역시 서구 둔산대로 117",
      latitude: 36.3660,
      longitude: 127.3870,
      safeTags: ["저GI 찰보리", "저염 강된장", "당뇨/고혈압 안심"],
      healthBenefit: "복합 탄수화물로 식후 인슐린 저항성 완화",
      nutrition: {
        menuName: "유기농 보약 솥밥 정식",
        calories: 415,
        carbohydrate: 55,
        sugars: 3,
        sodium: 350,
        protein: 17,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 3g, 나트륨 350mg",
      },
      tourApiContentId: "FD_DAEJEON_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-daejeon-1",
      name: "대전 한밭수목원 서원 힐링 둘레길",
      naverPlaceName: "한밭수목원",
      category: "산책로",
      description: "도심 속 최대 인공수목원의 완전 무장애 평지 흙길과 소나무 숲길",
      address: "대전광역시 서구 만년동 396",
      latitude: 36.3685,
      longitude: 127.3895,
      safeTags: ["완전 평지 0%", "피톤치드 숲길", "연속 벤치 완비"],
      healthBenefit: "식후 30분 완보로 근육 포도당 소모 촉진",
      tourApiContentId: "C_DAEJEON_01",
      isMajorRoute: true,
    },
    walkMinutes: 22,
    distanceMeters: 850,
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 혈당 32mg/dL 완화",
  },
  {
    id: "course-sejong-1",
    title: "세종 1코스: [대사증후군케어] 세종 청사 저염 우렁쌈밥 ➔ 세종호수공원 수상데크길",
    targetCondition: "당뇨, 고혈압 (식이섬유 섭취 & 탁 트인 호수 완보)",
    region: "세종/충청권",
    isLocal: true,
    restaurant: {
      id: "rest-sejong-1",
      name: "세종 청사 저염 우렁쌈밥 (호수공원점)",
      naverPlaceName: "세종특별자치시 다솜로 216",
      category: "안심식당",
      description: "세종시 안심식당 인증, 친환경 쌈채소 무한 리필과 천연 저염 강된장",
      address: "세종특별자치시 다솜로 216",
      latitude: 36.5010,
      longitude: 127.2640,
      safeTags: ["친환경 채소", "저염 우렁쌈", "대사증후군 케어"],
      healthBenefit: "풍부한 식이섬유로 장내 포도당 흡수 지연",
      nutrition: {
        menuName: "우렁 쌈채 정식",
        calories: 420,
        carbohydrate: 56,
        sugars: 3,
        sodium: 360,
        protein: 18,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 3g, 나트륨 360mg",
      },
      tourApiContentId: "FD_SEJONG_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-sejong-1",
      name: "세종호수공원 물빛섬 수상데크길",
      naverPlaceName: "세종호수공원",
      category: "산책로",
      description: "국내 최대 도심 호수 수면 위를 걷는 무장애 데크로드",
      address: "세종특별자치시 연기면 다솜로 216",
      latitude: 36.4980,
      longitude: 127.2680,
      safeTags: ["완전 평지 0%", "수상 데크", "야간 조명"],
      healthBenefit: "안정적인 유산소 보행으로 인슐린 감수성 개선",
      tourApiContentId: "C_SEJONG_01",
      isMajorRoute: true,
    },
    walkMinutes: 20,
    distanceMeters: 790,
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 혈당 스파이크 차단",
  },
  {
    id: "course-daegu-1",
    title: "대구 1코스: [당뇨·신장케어] 수성 들깨 순두부마을 ➔ 수성못 완만 힐링길",
    targetCondition: "당뇨, 고혈압 (고단백 저염식 & 호수 바람 완보)",
    region: "대구/경북권",
    isLocal: true,
    restaurant: {
      id: "rest-daegu-1",
      name: "수성 들깨 순두부마을 (수성못점)",
      naverPlaceName: "대구광역시 수성구 용학로 106",
      category: "안심식당",
      description: "대구시 안심식당, 국산콩 100% 갓 만든 순두부와 혈관 건강 들깨 옹심이",
      address: "대구광역시 수성구 용학로 106",
      latitude: 35.8300,
      longitude: 128.6160,
      safeTags: ["국산콩 순두부", "오메가3 들깨", "저염 조리"],
      healthBenefit: "식물성 단백질 공급 및 식후 혈당 급상승 방지",
      nutrition: {
        menuName: "전통 맷돌 순두부 정식",
        calories: 390,
        carbohydrate: 46,
        sugars: 2,
        sodium: 340,
        protein: 21,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 2g, 단백질 21g",
      },
      tourApiContentId: "FD_DAEGU_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-daegu-1",
      name: "대구 수성못 수변 데크 완만 둘레길",
      naverPlaceName: "수성못",
      category: "산책로",
      description: "호수를 둘러싼 2km 완전 평지 목재 데크와 왕버들 가로수길",
      address: "대구광역시 수성구 두산동 수성못",
      latitude: 35.8265,
      longitude: 128.6185,
      safeTags: ["완전 평지", "호수 데크길", "그늘막 벤치"],
      healthBenefit: "식후 20분 보행으로 하지 혈류 개선 및 혈압 안정",
      tourApiContentId: "C_DAEGU_01",
      isMajorRoute: true,
    },
    walkMinutes: 18,
    distanceMeters: 710,
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 1시간 혈당 28mg/dL 안정",
  },
  {
    id: "course-busan-1",
    title: "부산 1코스: [고혈압·심혈관케어] 해운대 기장 미역국 정찬 ➔ 동백섬 해안둘레길",
    targetCondition: "고혈압, 이상지질혈증 (칼륨 풍부 해조류 & 해안 평지 완보)",
    region: "부산/경남권",
    isLocal: true,
    restaurant: {
      id: "rest-busan-1",
      name: "해운대 기장 미역국 정찬 (동백점)",
      naverPlaceName: "부산광역시 해운대구 동백로 89",
      category: "안심식당",
      description: "부산시 안심식당, 조개와 전복으로 우려낸 천연 저염 미역국 정찬",
      address: "부산광역시 해운대구 동백로 89",
      latitude: 35.1550,
      longitude: 129.1500,
      safeTags: ["칼륨 풍부", "저염 해조류", "혈관 건강"],
      healthBenefit: "체내 과잉 나트륨 배출 및 혈액 정화",
      nutrition: {
        menuName: "자연산 가자미 미역국 밥상",
        calories: 410,
        carbohydrate: 52,
        sugars: 1,
        sodium: 370,
        protein: 23,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 1g, 단백질 23g",
      },
      tourApiContentId: "FD_BUSAN_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-busan-1",
      name: "해운대 동백섬 무장애 해안산책로",
      naverPlaceName: "동백섬",
      category: "산책로",
      description: "동백나무 숲과 푸른 바다를 조망하는 완만한 무장애 목재 데크길",
      address: "부산광역시 해운대구 우동 동백섬",
      latitude: 35.1520,
      longitude: 129.1530,
      safeTags: ["완만 해안데크", "동백나무 숲", "누리마루 조망"],
      healthBenefit: "바다 음이온 흡입 및 유산소 대사 촉진",
      tourApiContentId: "C_BUSAN_01",
      isMajorRoute: true,
    },
    walkMinutes: 20,
    distanceMeters: 800,
    slopeGrade: "완만(무장애)",
    expectedEffect: "혈관 탄력 개선 및 스트레스 호르몬 감소",
  },
  {
    id: "course-gwangju-1",
    title: "광주 1코스: [저염·혈류케어] 상무 약선 보리굴비 솥밥 ➔ 5·18기념공원 힐링길",
    targetCondition: "고혈압, 당뇨 (풍부한 미네랄 & 평탄 도심 숲길)",
    region: "광주/호남권",
    isLocal: true,
    restaurant: {
      id: "rest-gwangju-1",
      name: "상무 약선 보리굴비 솥밥 (상무지구점)",
      naverPlaceName: "광주광역시 서구 상무평화로 89",
      category: "안심식당",
      description: "광주시 안심식당 인증, 녹차물에 말아먹는 저염 보리굴비와 10가지 제철 나물",
      address: "광주광역시 서구 상무평화로 89",
      latitude: 35.1520,
      longitude: 126.8500,
      safeTags: ["녹차 카테킨", "저염 굴비", "나물밥상"],
      healthBenefit: "항산화 카테킨 성분으로 혈관 염증 완화",
      nutrition: {
        menuName: "녹차 보리굴비 약선 솥밥",
        calories: 425,
        carbohydrate: 54,
        sugars: 2,
        sodium: 380,
        protein: 24,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 2g, 단백질 24g",
      },
      tourApiContentId: "FD_GWANGJU_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-gwangju-1",
      name: "광주 5·18기념공원 단풍나무 무장애 둘레길",
      naverPlaceName: "5·18기념공원",
      category: "산책로",
      description: "울창한 도심 숲속 계단 없는 평지 데크로드와 정자 쉼터",
      address: "광주광역시 서구 상무민주로 61",
      latitude: 35.1550,
      longitude: 126.8530,
      safeTags: ["완전 평지 0%", "숲속 산책로", "비상벨 완비"],
      healthBenefit: "식후 20분 완보로 혈당 및 혈압 동시 안정",
      tourApiContentId: "C_GWANGJU_01",
      isMajorRoute: true,
    },
    walkMinutes: 18,
    distanceMeters: 720,
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 최고 혈당 27mg/dL 감소",
  },
  {
    id: "course-gangneung-1",
    title: "강원 1코스: [당뇨·고단백케어] 강릉 초당 전통순두부 ➔ 경포호수 무장애 둘레길",
    targetCondition: "당뇨, 고혈압 (식물성 단백질 & 호수 솔향기길)",
    region: "강원/동해안권",
    isLocal: true,
    restaurant: {
      id: "rest-gangneung-1",
      name: "강릉 초당 전통 저염순두부 (원조마을점)",
      naverPlaceName: "강원특별자치도 강릉시 초당순두부길 77",
      category: "안심식당",
      description: "동해 바닷물 천연 간수로 빚은 저나트륨 고단백 초당 순두부 밥상",
      address: "강원특별자치도 강릉시 초당순두부길 77",
      latitude: 37.7940,
      longitude: 128.9130,
      safeTags: ["천연 간수", "고단백 저염", "당뇨 안심"],
      healthBenefit: "혈당 스파이크를 원천 차단하는 최적의 단백질 식단",
      nutrition: {
        menuName: "전통 초당 순두부 백반",
        calories: 380,
        carbohydrate: 42,
        sugars: 2,
        sodium: 310,
        protein: 22,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 2g, 나트륨 310mg, 단백질 22g",
      },
      tourApiContentId: "FD_GANGNEUNG_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-gangneung-1",
      name: "강릉 경포호수 수변 무장애 둘레길",
      naverPlaceName: "경포호",
      category: "산책로",
      description: "호수와 솔밭을 둘러싼 완전 평지 목재 데크와 힐링 벤치",
      address: "강원특별자치도 강릉시 저동 경포호수",
      latitude: 37.7980,
      longitude: 128.9080,
      safeTags: ["완전 평지 0%", "솔숲 호수길", "무장애 데크"],
      healthBenefit: "솔향 피톤치드 흡입으로 심박수 및 혈압 안정",
      tourApiContentId: "C_GANGNEUNG_01",
      isMajorRoute: true,
    },
    walkMinutes: 20,
    distanceMeters: 820,
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 혈당 35mg/dL 완화",
  },
  {
    id: "course-jeonju-1",
    title: "전북 1코스: [고혈압·소화케어] 전주 약선 연잎밥 정식 ➔ 덕진공원 연화교 평지길",
    targetCondition: "고혈압, 소화기건강 (심신 안정 연잎향 & 연꽃호수 완보)",
    region: "전북/전주권",
    isLocal: true,
    restaurant: {
      id: "rest-jeonju-1",
      name: "전주 약선 연잎밥 정식 (덕진점)",
      naverPlaceName: "전북특별자치도 전주시 덕진구 덕진광장로 24",
      category: "안심식당",
      description: "전주시 안심식당, 유기농 찹쌀과 연잎의 은은한 향으로 찐 저염 약선 연잎밥",
      address: "전북특별자치도 전주시 덕진구 덕진광장로 24",
      latitude: 35.8470,
      longitude: 127.1230,
      safeTags: ["천연 연잎향", "저염 약선", "식이섬유 풍부"],
      healthBenefit: "혈관 정화 및 소화기 점막 보호",
      nutrition: {
        menuName: "유기농 연잎밥 정찬",
        calories: 410,
        carbohydrate: 55,
        sugars: 3,
        sodium: 330,
        protein: 16,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 3g, 나트륨 330mg",
      },
      tourApiContentId: "FD_JEONJU_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-jeonju-1",
      name: "전주 덕진공원 연화교 수변 평지길",
      naverPlaceName: "덕진공원",
      category: "산책로",
      description: "연꽃 호수 위를 가로지르는 전통 한옥풍 완전 평지 연화교와 수변 데크",
      address: "전북특별자치도 전주시 덕진구 덕진동1가 덕진공원",
      latitude: 35.8495,
      longitude: 127.1205,
      safeTags: ["완전 평지 0%", "연꽃 호수길", "무장애 데크"],
      healthBenefit: "시니어 관절 무리 없는 유산소 대사 촉진",
      tourApiContentId: "C_JEONJU_01",
      isMajorRoute: true,
    },
    walkMinutes: 16,
    distanceMeters: 650,
    slopeGrade: "완만(무장애)",
    expectedEffect: "식후 혈관 이완 및 혈압 안정",
  },
  {
    id: "course-suncheon-1",
    title: "전남 1코스: [자연치유·혈관케어] 순천 꼬막 나물정찬 ➔ 순천만습지 갈대숲길",
    targetCondition: "이상지질혈증, 고혈압 (타우린 풍부 & 갈대숲 평지 완보)",
    region: "전남/남해안권",
    isLocal: true,
    restaurant: {
      id: "rest-suncheon-1",
      name: "순천만 약선 나물정찬 (생태관점)",
      naverPlaceName: "전라남도 순천시 순천만길 512",
      category: "안심식당",
      description: "순천시 안심식당, 타우린이 풍부한 벌교 참꼬막과 남도 제철 나물 건강 밥상",
      address: "전라남도 순천시 순천만길 512",
      latitude: 34.9320,
      longitude: 127.5050,
      safeTags: ["타우린 풍부", "저염 남도밥상", "혈관 정화"],
      healthBenefit: "콜레스테롤 배출 및 간 기능 해독 지원",
      nutrition: {
        menuName: "자연산 꼬막 나물 정식",
        calories: 430,
        carbohydrate: 53,
        sugars: 3,
        sodium: 390,
        protein: 23,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 3g, 나트륨 390mg",
      },
      tourApiContentId: "FD_SUNCHEON_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-suncheon-1",
      name: "순천만습지 무장애 갈대숲 데크로드",
      naverPlaceName: "순천만습지",
      category: "산책로",
      description: "끝없이 펼쳐진 갈대숲 사이를 걷는 100% 완전 평지 목재 탐방로",
      address: "전라남도 순천시 순천만길 513-25",
      latitude: 34.9290,
      longitude: 127.5090,
      safeTags: ["완전 평지 0%", "갈대숲 데크", "바람 쉼터"],
      healthBenefit: "자연 치유 피톤치드와 규칙적 유산소 보행",
      tourApiContentId: "C_SUNCHEON_01",
      isMajorRoute: true,
    },
    walkMinutes: 22,
    distanceMeters: 880,
    slopeGrade: "완만(무장애)",
    expectedEffect: "혈류 순환 촉진 및 심폐 기능 강화",
  },
  {
    id: "course-jeju-1",
    title: "제주 1코스: [항산화·당뇨케어] 제주 올레 약선보말죽 ➔ 절물 삼나무 숲길",
    targetCondition: "당뇨, 대사증후군 (저칼로리 보말 & 피톤치드 삼림욕)",
    region: "제주도",
    isLocal: true,
    restaurant: {
      id: "rest-jeju-1",
      name: "제주 올레 저염 약선보말죽 (명품관)",
      naverPlaceName: "제주특별자치도 제주시 명림로 584",
      category: "안심식당",
      description: "제주 자연산 고메기(보말)의 진한 미네랄과 해초를 듬뿍 넣은 저염 웰빙 보말죽",
      address: "제주특별자치도 제주시 명림로 584",
      latitude: 33.4350,
      longitude: 126.6260,
      safeTags: ["미네랄 풍부", "저염 보말죽", "항산화 웰니스"],
      healthBenefit: "간 해독 및 소화 흡수 부담 최소화",
      nutrition: {
        menuName: "자연산 보말 약선죽 정식",
        calories: 360,
        carbohydrate: 48,
        sugars: 1,
        sodium: 290,
        protein: 19,
        sugarGrade: "안심",
        sodiumGrade: "안심",
        nutritionTip: "식약처 인증: 당류 1g, 나트륨 290mg 최상급 안심",
      },
      tourApiContentId: "FD_JEJU_01",
      isMajorRoute: true,
    },
    trail: {
      id: "trail-jeju-1",
      name: "절물자연휴양림 무장애 삼나무 데크길",
      naverPlaceName: "절물자연휴양림",
      category: "산책로",
      description: "50년 수령 삼나무 숲속을 걷는 100% 완전 평지 휠체어/시니어 무장애길",
      address: "제주특별자치도 제주시 명림로 584",
      latitude: 33.4390,
      longitude: 126.6300,
      safeTags: ["완전 평지 0%", "삼나무 피톤치드", "무장애 데크"],
      healthBenefit: "고농도 피톤치드 흡입으로 인슐린 감수성 극대화",
      tourApiContentId: "C_JEJU_01",
      isMajorRoute: true,
    },
    walkMinutes: 25,
    distanceMeters: 900,
    slopeGrade: "완만(무장애)",
    expectedEffect: "스트레스 완화 및 인슐린 분비 안정화",
  },
];

// 1박 2일 공식/블로그 검증 장기 웰니스 코스 (한국관광공사 Tour API searchStay2 연계)
export const INITIAL_MULTI_DAY_COURSES: MultiDayCourseSet[] = [
  {
    id: "multi-course-1",
    title: "1박 2일: [당뇨·혈관 케어] 남산 숲속 힐링 & 한옥 안심 스테이",
    duration: "1박 2일",
    targetCondition: "당뇨, 고혈압 (지속적 식단 & 운동 루틴)",
    stay: {
      id: "stay-1",
      name: "나인트리 레지던스 & 안심 스테이 명동",
      address: "서울특별시 중구 명동길 61",
      description: "객실 내 주방에서 저염/저당 건강식을 직접 조리할 수 있고, 인슐린 냉장 보관 및 피트니스 룸을 완비한 웰니스 공인 숙소",
      latitude: 37.5635,
      longitude: 126.9855,
      chkcooking: true,       // 객실 내 취사 가능 (저염식 직접 조리)
      roomrefrigerator: true, // 객실 내 냉장고 보유 (인슐린 의약품 보관)
      fitness: true,          // 피트니스 센터 보유 (식후 혈당 조절 걷기)
      safeBadges: ["🍳 객실 내 취사 가능", "❄️ 인슐린 안심 냉장고", "🏋️ 피트니스 센터 완비"],
      contact: "02-6967-0999",
    },
    days: [
      {
        day: 1,
        title: "1일차: 저당 안심식사 ➔ 남산 소나무길 완보 ➔ 숙소 체크인",
        description: "자연식으로 혈당 스파이크를 방어하고, 완경사 소나무길을 걸어 인슐린 감수성을 극대화합니다.",
        steps: [
          {
            type: "식사",
            name: "소담한 자연밥상 (점심)",
            description: "GI 50 이하 유기농 제철 나물쌈과 찰현미 솥밥",
            tags: ["당류 4g", "나트륨 380mg", "저염인증"],
          },
          {
            type: "산책",
            name: "남산 힐링 소나무 자락길 (오후)",
            description: "경사도 4.5% 미만의 휠체어/시니어 완만 무장애 목재 데크길 (30분)",
            tags: ["완경사 5%미만", "화장실 인접", "그늘쉼터"],
          },
          {
            type: "숙박",
            name: "나인트리 레지던스 체크인 (저녁)",
            description: "인슐린 약물 냉장 보관 후 객실 내 주방에서 안심 식단 조리 및 휴식",
            tags: ["취사 가능", "인슐린 냉장고", "피트니스 센터"],
          },
        ],
      },
      {
        day: 2,
        title: "2일차: 객실 저염 조식 ➔ 용산 호수 둘레길 회복 걷기",
        description: "숙소 피트니스에서 가벼운 스트레칭 후, 평탄한 용산가족공원 호수길을 걸으며 여행을 마무리합니다.",
        steps: [
          {
            type: "체험",
            name: "모닝 스트레칭 & 저염식 (오전)",
            description: "숙소 피트니스 룸에서 가벼운 유산소 및 객실 내 저당 조식",
            tags: ["실내 운동", "혈당 체크", "안심 조리"],
          },
          {
            type: "식사",
            name: "도심속 풀향기 건강식당 (점심)",
            description: "루틴 성분 풍부한 순메밀과 칼륨 배출 맑은 육수 정식",
            tags: ["염도 0.5%이하", "나트륨 310mg"],
          },
          {
            type: "산책",
            name: "용산가족공원 호수 둘레길 (오후)",
            description: "완벽한 평지 흙길과 호수 전망 벤치에서 즐기는 자율신경계 이완 산책 (25분)",
            tags: ["완벽 평지", "호수 뷰", "쉼터 완비"],
          },
        ],
      },
    ],
  },
];

// 헬스케어 지원 안심 숙소 목록 (취사 가능, 인슐린 냉장고, 피트니스 센터)
export const INITIAL_WELLNESS_STAYS: WellnessStay[] = [
  {
    id: "stay-1",
    name: "나인트리 프리미어 레지던스 명동",
    naverPlaceName: "나인트리 프리미어 호텔 명동",
    address: "서울특별시 중구 명동길 61",
    description: "전 객실 주방 완비로 저염식 직접 조리 가능, 인슐린 전용 냉장고 및 24시간 피트니스 센터 보유",
    latitude: 37.5635,
    longitude: 126.9855,
    chkcooking: true,
    roomrefrigerator: true,
    fitness: true,
    safeBadges: ["🍳 객실 취사 완비", "❄️ 인슐린 냉장고", "🏋️ 24h 피트니스"],
    contact: "02-6967-0999",
  },
  {
    id: "stay-2",
    name: "서머셋 팰리스 서울 (종로/인사동)",
    naverPlaceName: "서머셋팰리스 서울",
    address: "서울특별시 종로구 율곡로2길 7",
    description: "주방 조리 시설과 대형 냉장고, 실내 피트니스와 루프탑 산책로를 갖춘 장기 체류형 안심 레지던스",
    latitude: 37.5752,
    longitude: 126.9824,
    chkcooking: true,
    roomrefrigerator: true,
    fitness: true,
    safeBadges: ["🍳 풀옵션 주방", "❄️ 냉동/냉장고", "🏋️ 웰니스 피트니스", "🌿 루프탑 쉼터"],
    contact: "02-6730-8888",
  },
  {
    id: "stay-3",
    name: "남산 힐링 레지던스 스테이",
    naverPlaceName: "서울특별시 중구 퇴계로 18길 32",
    address: "서울특별시 중구 퇴계로 18길 32",
    description: "남산 둘레길 진입로 바로 앞, 독립 주방과 저온 약물 냉장고를 구비한 조용한 숲세권 힐링 숙소",
    latitude: 37.5588,
    longitude: 126.9848,
    chkcooking: true,
    roomrefrigerator: true,
    fitness: false,
    safeBadges: ["🍳 취사 가능", "❄️ 인슐린 냉장고", "🌲 남산 자락 바로 앞"],
    contact: "02-778-5522",
  },
  {
    id: "stay-4",
    name: "그랜드 앰배서더 웰니스 호텔",
    naverPlaceName: "앰배서더 서울 풀만 호텔",
    address: "서울특별시 중구 동호로 287",
    description: "전문 트레이너 상주 메디컬 피트니스와 실내 보행 트랙, 약물 냉장 보관 컨시어지 서비스 제공",
    latitude: 37.5601,
    longitude: 127.0034,
    chkcooking: false,
    roomrefrigerator: true,
    fitness: true,
    safeBadges: ["❄️ 의료 냉장 컨시어지", "🏋️ 메디컬 피트니스", "🏊 저충격 실내 트랙"],
    contact: "02-2275-1101",
  },
  {
    id: "stay-ansan-1",
    name: "엠블던 호텔 웰니스 레지던스 (안산)",
    naverPlaceName: "엠블던호텔",
    address: "경기도 안산시 단원구 중앙대로 757",
    description: "객실 내 인슐린 의약품 냉장고 구비, 피트니스 센터 완비 및 안산 호수공원 인접 웰니스 공인 호텔",
    latitude: 37.3175,
    longitude: 126.839,
    chkcooking: true,
    roomrefrigerator: true,
    fitness: true,
    safeBadges: ["🍳 조리 식기 완비", "❄️ 인슐린 냉장고", "🏋️ 피트니스 센터"],
    contact: "031-414-9000",
  },
];

// 관광명소 연계 웰니스 스탬프 퀘스트 및 칭호 리워드
export const INITIAL_WELLNESS_QUESTS: WellnessQuest[] = [
  {
    id: "quest-1",
    title: "남산 N서울타워 & 솔숲길 30분 안심 완보 퀘스트",
    description: "피톤치드 가득한 남산 소나무 자락길을 30분간 여유롭게 완보하여 식후 혈당을 안정화하세요.",
    landmarkName: "남산 서울타워 & 솔숲길",
    naverPlaceName: "N서울타워",
    category: "산책로/자연",
    address: "서울특별시 중구 남산공원길 105",
    latitude: 37.5512,
    longitude: 126.9882,
    targetDurationMinutes: 30,
    titleReward: "초록빛 혈관 수호자 🏅",
    badgeIcon: "🌲",
    isCompleted: false,
    progressMinutes: 0,
  },
  {
    id: "quest-2",
    title: "덕수궁 돌담길 & 정동 역사문화 20분 힐링 산책",
    description: "식사 후 계단 없는 완벽한 평지 돌담길을 20분간 산책하여 기립성 어지럼증을 예방하고 활력을 충전하세요.",
    landmarkName: "덕수궁 돌담길 & 정동길",
    naverPlaceName: "덕수궁 돌담길",
    category: "역사문화/도심",
    address: "서울특별시 중구 정동 덕수궁길 24",
    latitude: 37.5662,
    longitude: 126.9765,
    targetDurationMinutes: 20,
    titleReward: "도심 속 웰니스 탐험가 🌿",
    badgeIcon: "🏛️",
    isCompleted: false,
    progressMinutes: 0,
  },
  {
    id: "quest-3",
    title: "청계천 무장애 수변길 25분 활력 걷기",
    description: "물소리를 들으며 스트레스를 낮추고 수변 데크길을 25분간 걸어 모세혈관 순환을 촉진합니다.",
    landmarkName: "청계천 수변 산책로",
    naverPlaceName: "청계광장",
    category: "수변/도심",
    address: "서울특별시 중구 태평로1가 청계광장",
    latitude: 37.5691,
    longitude: 126.9786,
    targetDurationMinutes: 25,
    titleReward: "물빛 청량 활력왕 💧",
    badgeIcon: "🌊",
    isCompleted: false,
    progressMinutes: 0,
  },
];

